PRECEDENCE = ("BLOCKED_DECISION_MATERIAL_SEMANTIC_OR_AUTHORITY", "CONFLICTING_SAME_SCOPE_COMPONENT_EVIDENCE",
              "POSITIVE_AT_LEAST_ONE_COMMON_EWP_CONSTRAINT", "COMMON_SUPPORT_IDENTIFIED_NO_QUANTITATIVE_EWP_NARROWING",
              "COMPLEMENTARY_SOURCE_CONDITIONED_SUPPORTS_ONLY", "NEGATIVE_NO_COMMON_CROSS_CORPUS_CONSTRAINT")


def reduce_overall(components: list[dict]) -> str:
    tags = {item["overall_tag"] for item in components}
    selected = next((tag for tag in PRECEDENCE if tag in tags), "NEGATIVE_NO_COMMON_CROSS_CORPUS_CONSTRAINT")
    return "SCI_DATA_FUSION_001_" + selected

