"""EWP-POROSITY-PERMEABILITY-PRIOR-001 research-only analysis."""

STOP_AUTHORITY = "EWP_POROSITY_PERMEABILITY_PRIOR_001_STOP_SOURCE_AUTHORITY_MISMATCH"
MAX_CLAIM = "SOURCE_CONDITIONED_STATIC_POROSITY_AND_PERMEABILITY_PRIOR_QUALIFICATION_FOR_EWP_HYDRAULIC_SENSITIVITY"
