"""Explicit source-to-EWP mappings; no variable-name unit inference."""
FIELDS=["source","lineage_id","source_file","source_row_or_group","source_variable","source_definition","source_unit","measurement_or_derivation_method","dry_or_wet_state","initial_or_operating_state","total_or_connected_basis","intrinsic_apparent_or_effective_basis","source_geometry","source_coffee_and_roast_scope","preparation_and_compaction_scope","uncertainty_semantics","proposed_ewp_target","mapping_class","source_disposition","conversion_formula","observation_operator_id","observation_operator_inputs","observation_operator_output","observation_operator_closure_status","geometry_transfer_rule","viscosity_treatment","required_assumptions","transfer_limitations","primary_sensitivity_eligible","contextual_diagnostic_eligible","exclusion_reason","claim_limit"]
WADS="puckworks/data/wadsworth2026/wadsworth2026_table1_full.csv";VFIG="puckworks/data/vacaguerra2023a/Figure_12_Calculated_versus_experimental_dry_bed_porosity_validation_experiments.csv";VC1="puckworks/data/vacaguerra2023a/Table_C1_Extraction_conditions_from_permeability_experiments.csv";VPSD="puckworks/data/vacaguerra2023a/Table_1_Particle_size_distributions_used_in_extraction_experiments.csv"
VARIABLES=[
dict(source="Wadsworth",lineage_id="WADSWORTH_TABLE1_XCT_LBFLOW_UNTAMPED",source_file=WADS,source_variable="phi_T_total",source_definition="total void fraction segmented by XCT",source_unit="1",measurement_or_derivation_method="XCT_TOTAL_PORE_SEGMENTATION",dry_or_wet_state="DRY",initial_or_operating_state="SOURCE_NATIVE_UNTAMPED",total_or_connected_basis="TOTAL",intrinsic_apparent_or_effective_basis="NOT_APPLICABLE",proposed_ewp_target="coffee_bed.initial_porosity",mapping_class="SOURCE_CONDITIONED_PRIOR_ONLY",source_disposition="USEFUL_SOURCE_CONDITIONED_SUPPORT",primary_sensitivity_eligible="true",transfer_limitations="dry untamped XCT geometry is not wet operating porosity"),
dict(source="Wadsworth",lineage_id="WADSWORTH_TABLE1_XCT_LBFLOW_UNTAMPED",source_file=WADS,source_variable="phi_p_connected",source_definition="connected/percolating XCT pore fraction",source_unit="1",measurement_or_derivation_method="XCT_CONNECTED_PORE_SEGMENTATION",dry_or_wet_state="DRY",initial_or_operating_state="SOURCE_NATIVE_UNTAMPED",total_or_connected_basis="CONNECTED",intrinsic_apparent_or_effective_basis="NOT_APPLICABLE",proposed_ewp_target="coffee_bed.initial_porosity",mapping_class="CONTEXTUAL_BOUND_ONLY",source_disposition="CONTEXTUAL_BOUND_ONLY",primary_sensitivity_eligible="false",transfer_limitations="connected pore fraction is not EWP total porosity; no closed observation operator"),
dict(source="Wadsworth",lineage_id="WADSWORTH_TABLE1_XCT_LBFLOW_UNTAMPED",source_file=WADS,source_variable="k_m2",source_definition="connected-pore XCT/LBflow intrinsic permeability",source_unit="m^2",measurement_or_derivation_method="XCT_LBFLOW",dry_or_wet_state="DRY_GEOMETRY_FLOW_RECONSTRUCTION",initial_or_operating_state="SOURCE_NATIVE_UNTAMPED",total_or_connected_basis="CONNECTED",intrinsic_apparent_or_effective_basis="INTRINSIC_SOURCE_NATIVE",proposed_ewp_target="hydraulics.saturated_permeability_m2",mapping_class="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",source_disposition="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",primary_sensitivity_eligible="false",transfer_limitations="untamped directional XCT/LBflow K is not calibrated EWP wet effective K; direct substitution is stress testing only"),
dict(source="Vaca",lineage_id="VACA_FIG12_DRY_POROSITY_OPERATOR",source_file=VFIG,source_variable="measured_dry_bed_porosity",source_definition="experimentally measured dry-bed porosity",source_unit="1",measurement_or_derivation_method="CROSS_DEVICE_DRY_BED_MEASUREMENT",dry_or_wet_state="DRY",initial_or_operating_state="INITIAL_DRY",total_or_connected_basis="TOTAL_BED",intrinsic_apparent_or_effective_basis="NOT_APPLICABLE",proposed_ewp_target="coffee_bed.initial_porosity",mapping_class="SOURCE_CONDITIONED_PRIOR_ONLY",source_disposition="USEFUL_SOURCE_CONDITIONED_SUPPORT",primary_sensitivity_eligible="true",transfer_limitations="single material and devices; not wet operating porosity"),
dict(source="Vaca",lineage_id="VACA_FIG12_DRY_POROSITY_OPERATOR",source_file=VFIG,source_variable="calculated_dry_bed_porosity",source_definition="Eq.9/10 predicted dry-bed porosity under reviewed negated-beta convention",source_unit="1",measurement_or_derivation_method="SOURCE_OPERATOR_PREDICTION",dry_or_wet_state="DRY",initial_or_operating_state="INITIAL_DRY",total_or_connected_basis="TOTAL_BED",intrinsic_apparent_or_effective_basis="NOT_APPLICABLE",proposed_ewp_target="coffee_bed.initial_porosity",mapping_class="REQUIRES_OBSERVATION_OPERATOR",source_disposition="OBSERVATION_OPERATOR_REQUIRED_AND_CLOSED",primary_sensitivity_eligible="true",observation_operator_id="VACA_EQ9_EQ10_NEGATED_BETA_DRY_POROSITY",observation_operator_inputs="PSD alpha,beta and source compression conditions",observation_operator_output="dimensionless calculated dry-bed porosity",observation_operator_closure_status="CLOSED_FOR_SOURCE_CONDITIONED_SENSITIVITY",transfer_limitations="source-internal operator verification only; not wet operating porosity"),
dict(source="Vaca",lineage_id="VACA_TABLE_C1_DARCY_OPERATING_POINTS",source_file=VC1,source_variable="epsilon_0",source_definition="initial dry-bed porosity for extraction operating point",source_unit="1",measurement_or_derivation_method="SOURCE_REPORTED_INITIAL_DRY_STATE",dry_or_wet_state="DRY_INITIAL",initial_or_operating_state="INITIAL",total_or_connected_basis="TOTAL_BED",intrinsic_apparent_or_effective_basis="NOT_APPLICABLE",proposed_ewp_target="coffee_bed.initial_porosity",mapping_class="SOURCE_CONDITIONED_PRIOR_ONLY",source_disposition="USEFUL_SOURCE_CONDITIONED_SUPPORT",primary_sensitivity_eligible="true",transfer_limitations="source material and compaction specific; not wet operating porosity"),
dict(source="Vaca",lineage_id="VACA_TABLE_C1_DARCY_OPERATING_POINTS",source_file=VC1,source_variable="k_published_mu_m2",source_definition="Darcy K from Q, pressure, source length/area and mu=3.5e-3 Pa s",source_unit="m^2",measurement_or_derivation_method="DIRECT_DARCY_DERIVATION_FROM_OPERATING_POINT",dry_or_wet_state="SOURCE_EXTRACTION_OPERATING",initial_or_operating_state="OPERATING",total_or_connected_basis="BULK_BED",intrinsic_apparent_or_effective_basis="APPARENT_DARCY_SOURCE_NATIVE",proposed_ewp_target="hydraulics.saturated_permeability_m2",mapping_class="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",source_disposition="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",primary_sensitivity_eligible="false",viscosity_treatment="AS_PUBLISHED_3.5E-3_PA_S",transfer_limitations="source geometry and unpublished pump curve; stress support only"),
dict(source="Vaca",lineage_id="VACA_TABLE_C1_DARCY_OPERATING_POINTS",source_file=VC1,source_variable="k_ewp_reference_mu_m2",source_definition="same source Q, pressure, length and area with EWP reference viscosity",source_unit="m^2",measurement_or_derivation_method="VISCOSITY_CONVENTION_REEXPRESSION_NOT_NEW_MEASUREMENT",dry_or_wet_state="SOURCE_EXTRACTION_OPERATING",initial_or_operating_state="OPERATING",total_or_connected_basis="BULK_BED",intrinsic_apparent_or_effective_basis="APPARENT_DARCY_REEXPRESSED",proposed_ewp_target="hydraulics.saturated_permeability_m2",mapping_class="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",source_disposition="SOURCE_NATIVE_STRESS_SUPPORT_ONLY",primary_sensitivity_eligible="false",conversion_formula="K_reexpressed=K_published*mu_EWP/(3.5e-3 Pa s)",viscosity_treatment="EWP_REFERENCE_VISCOSITY_REEXPRESSION",transfer_limitations="not a unit conversion or new measurement; source geometry/pump limit remain"),
dict(source="Vaca",lineage_id="VACA_EQ11_POSTFIT_RECONSTRUCTION",source_file=VPSD,source_variable="Eq11_postfit_K",source_definition="modified Kozeny-Carman post-fit reconstruction with lambda=7.5",source_unit="m^2",measurement_or_derivation_method="POST_FIT_RECONSTRUCTION",dry_or_wet_state="DRY_MODEL_CONTEXT",initial_or_operating_state="SOURCE_NATIVE",total_or_connected_basis="BULK_BED",intrinsic_apparent_or_effective_basis="POST_FIT_EFFECTIVE",proposed_ewp_target="hydraulics.saturated_permeability_m2",mapping_class="CONTEXTUAL_BOUND_ONLY",source_disposition="CONTEXTUAL_BOUND_ONLY",primary_sensitivity_eligible="false",transfer_limitations="same-nine-point post-fit; not independent evidence; no refit")]
def build():
 out=[]
 for s in VARIABLES:
  r={k:"NOT_APPLICABLE" for k in FIELDS};r.update(source_row_or_group="ALL_RETAINED_ROWS",source_geometry="SOURCE_NATIVE_RETAINED",source_coffee_and_roast_scope="SOURCE_SPECIFIC",preparation_and_compaction_scope="SOURCE_SPECIFIC",uncertainty_semantics="AS_REPORTED_NO_INVENTED_CONFIDENCE",conversion_formula="IDENTITY_ONLY_WITHIN_IDENTICAL_SOURCE_QUANTITY",observation_operator_id="NONE",observation_operator_inputs="NONE",observation_operator_output="NONE",observation_operator_closure_status="NOT_REQUIRED",geometry_transfer_rule="EXPLICIT_EWP_FIXED_DOSE_OR_FIXED_GEOMETRY_DIAGNOSTIC",viscosity_treatment="NOT_APPLICABLE",required_assumptions="static source-conditioned sensitivity does not establish state equivalence",contextual_diagnostic_eligible="true",exclusion_reason="NONE" if s["primary_sensitivity_eligible"]=="true" else s["transfer_limitations"],claim_limit="SOURCE_CONDITIONED_SENSITIVITY_ONLY");r.update(s);out.append(r)
 validate(out);return out
def validate(rows):
 for r in rows:
  if r["mapping_class"]=="REQUIRES_OBSERVATION_OPERATOR" and r["primary_sensitivity_eligible"]=="true" and (r["observation_operator_closure_status"]!="CLOSED_FOR_SOURCE_CONDITIONED_SENSITIVITY" or "NONE" in (r["observation_operator_inputs"],r["observation_operator_output"])):raise ValueError("EWP_POROSITY_PERMEABILITY_PRIOR_001_UNCLOSED_OPERATOR_PRIMARY_ELIGIBILITY")
 return True
