#!/usr/bin/env python3
"""Deterministically emit C2-R1 governance and test-authority records."""
import argparse,csv,hashlib,json,os,platform,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; DOC=ROOT/'docs/analysis/xsv_waszkiewicz_dynamic_hyd_001'
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(name,obj): (DOC/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def main():
 p=argparse.ArgumentParser();p.add_argument('--evidence-root',type=Path,required=True);p.add_argument('--final-commit',default='PENDING');p.add_argument('--final-tree',default='PENDING');a=p.parse_args();e=a.evidence_root;pre=e/'pre_c2_test_authority'
 owner={'adjudication_id':'XSV-WASZKIEWICZ-DYNAMIC-HYD-001-C2-R1','owner_authorization':'OWNER_ADJUDICATION_ACCEPT_R2_RETROSPECTIVE_TEST_IDENTITY_EVIDENCE_NONRECOVERABLE','exact_candidate_commit':'e4667eee315ecb8c93ba9be7c1385e04f12ffcca','exact_candidate_tree':'430397d9b4b9de14a4e85df2f75a709ae8c21802','historical_R2_result':{'reported_passed':1092,'reported_skipped':2,'discovered_test_ID_manifest_retained':False,'per_test_result_manifest_retained':False,'skip_ID_manifest_retained':False,'complete_environment_snapshot_retained':False,'identity_level_reconstruction_possible':False,'result_rejected_as_false':False,'usable_as_current_test_authority':False,'classification':'HISTORICAL_AGGREGATE_WITHOUT_RECONSTRUCTABLE_TEST_IDENTITY_AUTHORITY'},'supported_pre_C2_authority':{'python_executable':'/usr/bin/python3','python_version':'3.12.3','numpy_version':'1.26.4','scipy_version':'1.11.4','discovered_test_count':1119,'tests_run':1119,'passed':1116,'skipped':3,'failed':0,'errors':0,'repeat_execution_same_totals':True,'classification':'REPRODUCIBLE_PINNED_SUPPORTED_PRE_C2_TEST_AUTHORITY'},'waiver_scope':{'waived':'EXACT_RETROSPECTIVE_R2_TEST_IDENTITY_RECONSTRUCTION','not_waived':['current_test_ID_manifest','current_per_test_result_manifest','current_skip_ID_and_reason_manifest','current_environment_snapshot','processing_machine_contract','four_semantic_rejection_tests','scientific_invariance','full_supported_environment_execution','hosted_CI','independent_bounded_addendum_rereview']},'scientific_effect':'NONE','model_result_changed':False,'successor_changed':False,'home_lab_status_changed':False}
 dump('C2_R1_TEST_AUTHORITY_OWNER_ADJUDICATION.json',owner)
 (DOC/'C2_R1_TEST_AUTHORITY_OWNER_ADJUDICATION.md').write_text('# C2-R1 owner adjudication\n\nThe retained R2 evidence supports its historical aggregate of 1,092 passed and two skipped, but retains no discovered-ID manifest, per-test results, skip identities/reasons, complete environment, or complete loader snapshot. Exact identity reconstruction is therefore impossible. This evidence limitation does not declare the aggregate false. It is not a failed current suite, a scientific defect, or permission to fabricate identities.\n\nOnly `EXACT_RETROSPECTIVE_R2_TEST_IDENTITY_RECONSTRUCTION` is waived. All prospective identity/result/skip retention, environment reproduction, processing contract, four semantic rejections, scientific invariance, full execution, hosted CI, and independent bounded rereview remain required.\n')
 env={'os':platform.platform(),'kernel':platform.release(),'architecture':platform.machine(),'python_executable':'/usr/bin/python3','python_version':platform.python_version(),'sys_path':sys.path,'environment_kind':'system','package_versions':{'numpy':'1.26.4','scipy':'1.11.4'},'environment_variables':{k:os.environ.get(k,'') for k in ('LANG','LC_ALL','PYTHONDONTWRITEBYTECODE','PATH')},'working_directory':str(ROOT),'checkout_path':str(ROOT),'locale':os.environ.get('LANG',''),'test_command':"PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m unittest discover -s tests -p 'test_*.py'",'generated_files_present_before_discovery':[],'source_commit':'e4667eee315ecb8c93ba9be7c1385e04f12ffcca','source_tree':'430397d9b4b9de14a4e85df2f75a709ae8c21802'};dump('C2_R1_SUPPORTED_PRE_C2_ENVIRONMENT.json',env)
 auth={'classification':'REPRODUCIBLE_PINNED_SUPPORTED_PRE_C2_TEST_AUTHORITY','source_commit':env['source_commit'],'source_tree':env['source_tree'],'python_executable':'/usr/bin/python3','python_version':'3.12.3','numpy_version':'1.26.4','scipy_version':'1.11.4','authoritative_command':env['test_command'],'discovered_test_count':1119,'tests_run':1119,'passed':1116,'skipped':3,'failed':0,'errors':0,'repeated_discovery_count':2,'repeated_discovery_identical':True,'repeated_full_run_count':2,'repeat_execution_same_totals':True,'unique_test_ID_manifest_sha256':sha(pre/'DISCOVERED_TEST_IDS.txt'),'source_index_sha256':sha(pre/'TEST_SOURCE_INDEX.csv'),'result_manifest_sha256':sha(pre/'TEST_RESULTS.csv'),'skipped_test_manifest_sha256':sha(pre/'SKIPPED_TESTS.csv')};dump('C2_R1_SUPPORTED_PRE_C2_TEST_AUTHORITY.json',auth)
 muts=[('INDEPENDENT_TIME_ROW_BOOTSTRAP','R2 required rejection of independent time-row resampling',['C1_REVIEW_MANDATED_METHODS_ADDENDUM.json'],'set bootstrap.time_rows_resampled=true','XSV_BOOTSTRAP_TIME_ROW_INDEPENDENCE_FORBIDDEN'),('LEGACY_RANKING_STABLE_FALSE','R2 required rejection of legacy ranking_stable:false',['PROCESSING_ROBUSTNESS.json'],'add ranking_stable=false','XSV_PROCESSING_OBSOLETE_FIELD'),('BROAD_DYNAMIC_ABSENCE_WORDING','R2 required rejection of broad dynamic-absence wording',['summary.json'],'set scope.all_time_dependence_ruled_out=true','XSV_BROAD_DYNAMIC_ABSENCE_CLAIM_FORBIDDEN'),('SOURCE_MODEL_GROUPED_PREDICTION_RELABEL','R2 required rejection of source-model grouped-prediction relabeling',['SOURCE_MODEL_PARITY.json'],'relabel privilege as grouped predictive validation','XSV_SOURCE_MODEL_GROUPED_PREDICTION_RELABEL_FORBIDDEN')]
 dump('C2_R1_SEMANTIC_MUTATION_REQUIREMENTS.json',{'source_review':'XSV-WASZKIEWICZ-DYNAMIC-HYD-001-R2','source_review_checksum_manifest_sha256':'34817dbf1141d219682ad63665f01e6269965bd27f573743e2611ea565288413','reviewed_commit':'e4667eee315ecb8c93ba9be7c1385e04f12ffcca','requirements_count':4,'mutations':[{'mutation_id':m,'review_requirement_reference':r,'target_artifacts':t,'mutation_operation':o,'production_validator':'scripts/validate_xsv_waszkiewicz_dynamic_hyd_001.py','expected_error_code':c,'positive_control_test_id':f'test_{m.lower()}_control','negative_mutation_test_id':f'test_{m.lower()}_rejected'} for m,r,t,o,c in muts]})
 correction={'record_type':'C2_R1_OWNER_ADJUDICATED_FINAL_MERGE_READINESS_CORRECTION','parent_task':'XSV-WASZKIEWICZ-DYNAMIC-HYD-001','C1_correction':'XSV-WASZKIEWICZ-DYNAMIC-HYD-001-C1','R2_rereview':'XSV_WASZKIEWICZ_DYNAMIC_HYD_001_R2_INDEPENDENT_REREVIEW_CORRECTION_REQUIRED','failed_C2_stop':'XSV_WASZKIEWICZ_DYNAMIC_HYD_001_C2_STOP_TEST_AUTHORITY_UNRESOLVED','owner_adjudication':owner['owner_authorization'],'evidence_gap':'R2 exact test identities nonrecoverable','waived_requirement':owner['waiver_scope']['waived'],'non_waived_requirements':owner['waiver_scope']['not_waived'],'supported_pre_C2_test_authority':auth,'processing_contract_correction':'REQUIRED_AND_IMPLEMENTED','four_semantic_rejection_tests':'FOUR_OF_FOUR_REQUIRED','final_test_authority':'POPULATED_AT_FINALIZATION','scientific_invariance_ledger':'POPULATED_AT_FINALIZATION','scientific_result_changed':False,'development_consequence':'FIXED_RESISTANCE_RETAINED_BY_PARSIMONY','successor':'EWP-POROSITY-PERMEABILITY-PRIOR-001','home_lab_status':'DEFER_HOME_LAB_HIGHER_VALUE_EXISTING_DATA_TASKS_READY','final_candidate_commit':a.final_commit,'final_candidate_tree':a.final_tree,'independent_addendum_required':True,'merge_performed':False,'successor_execution':False};dump('C2_R1_CORRECTION_RECORD.json',correction)
 (DOC/'C2_R1_CORRECTION_RECORD.md').write_text('# C2-R1 correction record\n\n`C2_R1_OWNER_ADJUDICATED_FINAL_MERGE_READINESS_CORRECTION`. This is a machine-contract, semantic-validation, and present test-authority correction, not new science. The historical evidence gap and narrow waiver are recorded without declaring the R2 aggregate false. Scientific result, fixed-resistance consequence, successor, and home-lab status are unchanged. Merge remains false and bounded independent addendum rereview remains required.\n')
if __name__=='__main__': main()
