"""Deterministic Phase-A artifact producer; Phase B fails closed when authority is ineligible."""
from __future__ import annotations
import argparse,csv,json,pathlib,subprocess,sys
from .core import *

def write_json(p,v): pathlib.Path(p).write_bytes(canonical(v))
def write_csv(p,rows):
    with pathlib.Path(p).open("w",newline="",encoding="utf-8") as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
def git(repo,*args): return subprocess.check_output(["git","-C",str(repo),*args],text=True).strip()

def main(argv=None):
 p=argparse.ArgumentParser(); p.add_argument("--repo",type=pathlib.Path,required=True); p.add_argument("--puckworks",type=pathlib.Path,required=True); p.add_argument("--source-root",type=pathlib.Path,required=True); p.add_argument("--output",type=pathlib.Path,required=True); p.add_argument("--phase",choices=("a","b"),default="a"); p.add_argument("--freeze-sha256"); p.add_argument("--audit-file",type=pathlib.Path)
 a=p.parse_args(argv); out=a.output; out.mkdir(parents=True,exist_ok=True)
 source_paths={
  "ExperimentalData_validation.mat":a.source_root/"MATLAB_Code/ExperimentalData_validation.mat",
  "MassData_modelval.mat":a.source_root/"Experimental_data_validation/Decent & scale data/MassData_modelval.mat",
  "DesignOfExperiments_Validation_03_22.xlsx":a.source_root/"Experimental_data_validation/Decent & scale data/DesignOfExperiments_Validation_03_22.xlsx",
  "getExperimentalData_validation.m":a.source_root/"MATLAB_Code/getExperimentalData_validation.m",
  "GetMassScale_modelval.m":a.source_root/"Experimental_data_validation/Decent & scale data/GetMassScale.m",
  "ReadMassTimeFromScale.m":a.source_root/"Experimental_data_validation/Decent & scale data/ReadMassTimeFromScale.m"}
 actual={n:sha(pth) for n,pth in source_paths.items() if pth.is_file()}
 if actual!=EXPECTED: raise RuntimeError(f"external source unavailable or mismatched: {actual}")
 if git(a.puckworks,"rev-parse","HEAD")!="2058d0e947ee9eb92c52d64f6165b810f1fb4732" or git(a.puckworks,"rev-parse","HEAD^{tree}")!="a6ffb312473b15be43c1571a893b19873ea47c5a": raise RuntimeError("Puckworks authority mismatch")
 pred=a.repo/"docs/analysis/obs_pannusch_fraction_window_001/QUALIFICATION_FREEZE.json"
 if sha(pred)!="c0ad3033a1b1c33d56d9ea2e8d311688603d98ed038428392fe93a1fe582a306": raise RuntimeError("predecessor freeze mismatch")
 reg=candidate_registry(); code_hash=sha(pathlib.Path(__file__).with_name("core.py"))
 for r in reg:r["code_hash"]=code_hash
 semantics=[
 {"semantic_id":"PROGRAMMED_ENDPOINTS","condition_id_or_scope":"PRED-C01..C08","physical_shot_id_or_scope":"all shots","source_file":"DesignOfExperiments_Validation_03_22.xlsx","source_sha256":EXPECTED["DesignOfExperiments_Validation_03_22.xlsx"],"source_object_function_sheet":"DoE / normalized prediction_conditions","exact_source_locator":"programmed start/end temperature and flow columns","source_field_or_expression":"flow_start_mL_s; flow_end_mL_s","source_value_class":"PROGRAMMED_MACHINE_INSTRUCTION_NOT_MEASURED_INLET_OR_PUCK_FACE_FLOW","source_units":"mL/s","clock_name":"programme clock unresolved","clock_origin":"UNRESOLVED","support_start":"UNRESOLVED","support_end":"UNRESOLVED","physical_side":"machine instruction","measurement_or_derivation":"programmed","published_processing_role":"design labels/scalar start passed to published validation model","Pannusch_model_input_role":"scalar start only","admissible_as_Q_t":"NO_NONIDENTITY","eligibility_status":"IDENTITY_ONLY_PRIMARY;RAMP_INELIGIBLE","evidence_class":"SOURCE_PROGRAMMED","conclusion":"endpoints do not define an exact time history","failure_reason":"no ramp coordinate, zero, duration, support, or holds","rights":RIGHTS,"target_exposure":"TARGET_EXPOSED;SOURCE_INTERNAL"},
 {"semantic_id":"MASSDATA_FLOW","condition_id_or_scope":"PRED-C01..C08","physical_shot_id_or_scope":"24 shots","source_file":"GetMassScale_modelval.m;MassData_modelval.mat","source_sha256":EXPECTED["GetMassScale_modelval.m"]+";"+EXPECTED["MassData_modelval.mat"],"source_object_function_sheet":"released mass-scale script / MassData[1:24]","exact_source_locator":"dm_dt=2*f.a.*tfit+f.b; flow=dm_dt; MassData(field).flow=flow","source_field_or_expression":"MassData.flow vector","source_value_class":"BEVERAGE_MASS_DERIVED_OUTFLOW_TIMING","source_units":"g/s","clock_name":"mass-fit time","clock_origin":"selected scale segment rebased to first sample","support_start":"0 s","support_end":"per-shot MassData.time end","physical_side":"beverage scale outflow","measurement_or_derivation":"quadratic fitted derivative","published_processing_role":"copied to run.flow; not used as extraction-model Q","Pannusch_model_input_role":"none authorized","admissible_as_Q_t":"NO","eligibility_status":"INELIGIBLE","evidence_class":"SOURCE_DERIVED_FIT","conclusion":"vector, not scalar; derived beverage mass rate, not inlet volumetric flow","failure_reason":"physical side, density conversion, and model-Q authority absent","rights":RIGHTS,"target_exposure":"TARGET_EXPOSED;SOURCE_INTERNAL"},
 {"semantic_id":"MASS_QUADRATIC","condition_id_or_scope":"PRED-C01..C08","physical_shot_id_or_scope":"24 shots","source_file":"GetMassScale_modelval.m","source_sha256":EXPECTED["GetMassScale_modelval.m"],"source_object_function_sheet":"released mass-scale script","exact_source_locator":"mass/time rebasing; fit(x^2,x); tE inversion","source_field_or_expression":"m(t)=a*t^2+b*t; dm/dt=2*a*t+b","source_value_class":"BEVERAGE_MASS_DERIVED_OUTFLOW_TIMING;DERIVED_NOT_INLET_FLOW;CONTEXT_ONLY","source_units":"m:g; t:s; derivative:g/s","clock_name":"mass-fit/fraction clock","clock_origin":"selected scale segment first sample","support_start":"0 s","support_end":"fit tEnd","physical_side":"beverage scale","measurement_or_derivation":"quadratic fit and derivative","published_processing_role":"tE/fraction timing; derivative copied for context","Pannusch_model_input_role":"none authorized","admissible_as_Q_t":"NO","eligibility_status":"GATED_INELIGIBLE_BY_CURRENT_AUTHORITY","evidence_class":"SOURCE_DERIVED_FIT","conclusion":"m(t) and tE timing qualified; dm/dt remains context-only","failure_reason":"0.98 plotting conversion is neither stored MassData.flow nor published Pannusch-Q mapping","rights":RIGHTS,"target_exposure":"TARGET_EXPOSED;SOURCE_INTERNAL"}]
 clock={"task_id":TASK,"status":"FAIL_CLOSED_NONIDENTITY","programme_coordinate":"NOT_DEFINED_BY_RELEASED_SOURCE","programme_time_zero":"UNRESOLVED","solver_time_zero":"first requested t_bound; physical mapping to programme unresolved","mass_fit_zero":"first selected beverage-scale fit sample","fraction_clock_zero":"same derived mass-fit zero","ramp_start_s":"UNRESOLVED","ramp_end_s":"UNRESOLVED","ramp_duration_s":"UNRESOLVED","pre_ramp_hold":"UNRESOLVED","post_ramp_hold":"UNRESOLVED","support_over_solver_intervals":False,"prohibited_substitutions":["final tE as ramp duration","chemistry-fitted lag/offset","unsupported extrapolation","shared zero because clocks use seconds"],"evidence":["workbook DoE endpoint labels","GetMassScale_modelval.m mass/time rebase","getExperimentalData_validation.m scalar flow_start model use"]}
 authority={"task_id":TASK,"ewp_base_commit":"c81a1e3af1e55bac81e12443e26f3e45f43319e6","ewp_base_tree":"1eb780cd0704e84866508816d240c10f6b749204","later_unrelated_commits":[],"puckworks_commit":git(a.puckworks,"rev-parse","HEAD"),"puckworks_tree":git(a.puckworks,"rev-parse","HEAD^{tree}"),"pannusch_source_subset_manifest_sha256":sha(a.puckworks/"puckworks/data/pannusch2024/source_inputs.csv"),"external_source_sha256":actual,"predecessor_freeze_sha256":sha(pred),"puckworks_solver_sha256":sha(a.puckworks/"puckworks/models/pannusch2024/solver.py"),"runtime_lock_sha256":sha(a.repo/"dependencies/puckworks.lock.json"),"source_rights":RIGHTS}
 contract={"task_id":TASK,"governance_class":"G1","scientific_invariant":"NO_GOVERNING_PHYSICS_CHANGE","change_declaration":"SOURCE_SCENARIO_CHANGE_ONLY","claim_ceiling":"SOURCE_INTERNAL_FLOW_HISTORY_QUALIFICATION_ONLY","always_state":list(REQUIRED_CLAIMS),"cohorts":{"retained_residual_primary":list(PRIMARY),"programmed_ramp_identification":list(RAMP),"excluded":list(EXCLUDED)},"assay_fraction_ids":list(ASSAY_IDS),"analytes":["caffeine","trigonelline"],"metrics":{"primary":"condition-balanced physical-shot RMSE positions 2,5,6","continuity":"all six","bootstrap":{"replicates":2000,"rng":"NumPy PCG64","seed":20260830,"resampling":"condition then physical shot; retain analytes and complete vectors"}},"materiality":{"relative_improvement":0.1,"paired_interval":"strictly below zero","maximum_fraction_conditions_worse":0.25,"loco":"all beneficial"}}
 sys.path.insert(0,str(a.puckworks)); import numpy as np
 from puckworks.models.pannusch2024 import solver
 params=solver._solute_params()["caffeine"]; parity=[]
 for temp,flow,bounds in ((86.0,1.7,[0,2,4,7]),(92.0,2.3,[0,1.5,3.5,6])):
  raw=np.asarray(solver.simulate_fractions(temp,flow,bounds,dict(params),8.0,solver.GRINDS[1.7]),float)
  qt=np.asarray(solver.simulate_fractions_qt(temp,lambda _t,q=flow:q,bounds,dict(params),8.0,solver.GRINDS[1.7]),float)
  qt2=np.asarray(solver.simulate_fractions_qt(temp,lambda _t,q=flow:q,bounds,dict(params),8.0,solver.GRINDS[1.7]),float)
  nr=raw/raw.sum(); nq=qt/qt.sum()
  parity.append({"temperature_C":temp,"flow_mL_s":flow,"bounds_s":";".join(map(str,bounds)),"raw_max_abs":format(float(np.max(np.abs(raw-qt))),".17g"),"normalized_share_max_abs":format(float(np.max(np.abs(nr-nq))),".17g"),"deterministic_rerun_max_abs":format(float(np.max(np.abs(qt-qt2))),".17g"),"hard_ceiling":"1e-6","frozen_tolerance":"1e-8","status":"PASS" if np.max(np.abs(nr-nq))<=1e-8 else "FAIL"})
 if any(x["status"]!="PASS" for x in parity): raise RuntimeError("constant-q parity gate failed")
 parity_max=max(float(x["normalized_share_max_abs"]) for x in parity)
 freeze={"task_id":TASK,"authority":authority,"semantic_conclusions":semantics,"clock_map":clock,"candidate_registry":reg,"predecessor_boundary_reference":{"artifact":"docs/analysis/obs_pannusch_fraction_window_001/WINDOW_QUALIFICATION.csv","freeze_sha256":sha(pred),"all_ten_boundaries_for_24_shots":True},"frozen_kinetics_parameters_grind":"exact Puckworks authority; March grind=1.7; unchanged","legacy_baseline":"Q0 scalar programmed start; predecessor 144-row reproduction frozen","cohort_roles":contract["cohorts"],"normalization":"max(concentration,0)*measured fraction mass; normalize six assayed masses","metrics":contract["metrics"],"numerical_gates":{"constant_q_normalized_share_ceiling":1e-6,"frozen_tolerance":1e-8,"observed_max_difference":parity_max,"test_cases":parity},"decision_thresholds":contract["materiality"],"result_classes":["FLOW_AUTHORITY_INELIGIBLE"],"prohibited_post_score_changes":["lag","offset","multiplier","smoothing","density chosen from performance","extrapolation"],"code_hashes":{"core":code_hash,"runner":sha(__file__)},"chemistry_targets_accessed":False,"phase_b":"PROHIBITED_NO_ELIGIBLE_NONIDENTITY_CANDIDATE"}
 pending_hash=hashlib.sha256(canonical(freeze)).hexdigest()
 if a.audit_file:
  audit=json.loads(a.audit_file.read_text())
  if audit.get("status")!="PASS" or audit.get("audited_pending_freeze_sha256")!=pending_hash: raise RuntimeError("audit does not bind pending freeze")
  freeze["audit_result"]={"status":"PASS","audit_sha256":sha(a.audit_file),"audited_pending_freeze_sha256":pending_hash}
 write_json(out/"TASK_CONTRACT.json",contract); write_json(out/"DATA_AVAILABILITY_PREFLIGHT.json",{"task_id":TASK,"status":"AVAILABLE_AND_HASH_VERIFIED","sources":actual,"rights":RIGHTS}); write_json(out/"DATA_AUTHORITY.json",authority); write_csv(out/"FLOW_SEMANTICS.csv",semantics); write_json(out/"FLOW_CLOCK_QUALIFICATION.json",clock); write_json(out/"FLOW_CANDIDATE_REGISTRY.json",{"task_id":TASK,"candidates":reg}); write_csv(out/"CONSTANT_FLOW_PARITY.csv",parity); write_json(out/"QUALIFICATION_FREEZE.json",freeze)
 pending=sha(out/"QUALIFICATION_FREEZE.json")
 if a.audit_file:
  empty=[{"candidate_id":"NONE","cohort":"RETAINED_RESIDUAL_PRIMARY","status":"NOT_SCORED_FLOW_AUTHORITY_INELIGIBLE","reason":"no eligible nonidentity candidate; Phase B prohibited"}]
  write_csv(out/"FLOW_HISTORY_RESULTS.csv",empty); write_csv(out/"METRIC_RESULTS.csv",empty)
  disposition=classify_overall(reg)
  decision={"task_id":TASK,"scientific_disposition":disposition,"qualification":"COMPLETE_SOURCE_AUTHORITY_INELIGIBLE","materiality":"NOT_ADJUDICATED_NO_ELIGIBLE_NONIDENTITY_INPUT","retained_residual_conclusion":"NOT_EXPLAINED; QP is exact identity on C01/C02/C05/C06 and other nonidentity candidates are ineligible","programmed_ramp_conclusion":"NOT_SCORED; source endpoints lack authorized time coordinate/support/clock mapping","next_action":"XSV-PANNUSCH-EWP-INPUT-MAPPING-001","next_action_implemented":False,"freeze_sha256":pending,"audit_sha256":sha(a.audit_file),"claim_ceiling":"SOURCE_INTERNAL_FLOW_HISTORY_QUALIFICATION_ONLY","claims":list(REQUIRED_CLAIMS),"production_adoption":False}
  write_json(out/"DECISION.json",decision)
  write_json(out/"ATTEMPT_LOG.json",{"task_id":TASK,"attempts":[{"attempt":1,"phase_a":"PASS","audit":"PASS","phase_b":"PROHIBITED_BY_FROZEN_FLOW_AUTHORITY","material_corrections":0}]})
  write_json(out/"summary.json",{"task_id":TASK,"disposition":disposition,"freeze_sha256":pending,"audit_sha256":sha(a.audit_file),"eligible_candidates":["Q0_LEGACY_CONSTANT_START (baseline only)"],"ineligible_nonidentity_candidates":[x["candidate_id"] for x in reg[1:]],"phase_b":False,"parity_max_normalized_share_difference":parity_max,"retained_residual_explained":False,"next_action":"XSV-PANNUSCH-EWP-INPUT-MAPPING-001","claims":list(REQUIRED_CLAIMS)})
  (out/"RESULT.md").write_text(f"""# {TASK} result

`{disposition}`.

Released source establishes programmed flow endpoints as machine instructions, not measured inlet or puck-face flow. It supplies no ramp coordinate, programme zero, duration, support, or pre/post holds, so C07/C08 cannot be encoded as an exact source schedule. `MassData.flow` is not a scalar: the mass-scale script stores the vector `dm/dt = 2 a t + b` from a quadratic fit to beverage scale mass, in g/s. The script's `/0.98` conversion is plotted but not stored, and released extraction processing only copies the stored vector; it does not use it as Pannusch Q. Beverage outflow is not authorized as inlet flow, no applicable mass-to-volume conversion is established, and the scale, programme, and solver clocks are not mapped.

Therefore Q0 is the only eligible entry and is a baseline, not a nonidentity candidate. QP is exactly Q0 on C01/C02/C05/C06 and ineligible on C07/C08. The volume-equivalent diagnostic is gated off; QM and QD are ineligible. Phase B was prohibited before chemistry access, so no chemistry scores, winner selection, or retained-residual explanation were manufactured. Constant-q `simulate_fractions_qt` parity passed the frozen 1e-8 tolerance (hard ceiling 1e-6), with observed maximum normalized-share difference {parity_max:.17g}.

The existing scalar-start treatment is retained. `XSV-PANNUSCH-EWP-INPUT-MAPPING-001` is selected, not implemented. TARGET_EXPOSED; SOURCE_INTERNAL; NOT INDEPENDENT VALIDATION; NOT PHYSICAL VALIDATION; NOT HYDRAULIC VALIDATION; NOT PUCK_FACE_FLOW VALIDATION; NOT PRODUCTION QUALIFICATION. No production adoption occurred.
""",encoding="utf-8",newline="\n")
 if a.phase=="b": raise RuntimeError("Phase B prohibited: no source-eligible nonidentity flow candidate")
 print(pending)

if __name__=="__main__": main()
