"""EWP-REAL-WORLD-BOUNDARIES-001 research-only analysis."""

TASK_ID = "EWP-REAL-WORLD-BOUNDARIES-001"
PROTOCOL_ID = "EWP_RWB_001_PROTOCOL_V1"
CLAIM_CEILING = (
    "RECENT_PUBLIC_COHORT_BOUNDARY_QUALIFICATION_AND_"
    "POROSITY_CONDITIONED_EWP_HYDRAULIC_RESPONSE_MAPPING"
)
