#!/usr/bin/env python3
"""Add explicitly declared record-level contracts for correction administration."""
from __future__ import annotations
import argparse,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from tools.validation.val001.framework import canonical_json,load_json
from tools.validation.val001.normative import ASSIGNMENT_REGISTRY,NORMATIVE_REGISTRY

DECLARATIONS=[
 (63,"validation/val001/VAL_001_NORMATIVE_SCHEMA_CONTRACT_REGISTRY.json","NORMATIVE_SCHEMA_CONTRACT_REGISTRY","espresso.val001.normative_schema_contract_registry.v1",["schema_version","record_id","allowed_origins","prohibited_origins","contracts","record_bindings","counts"]),
 (64,"validation/val001/VAL_001_IMMUTABLE_PROFILE_ASSIGNMENT_REGISTRY.json","IMMUTABLE_PROFILE_ASSIGNMENT_REGISTRY","espresso.val001.immutable_profile_assignment_registry.v1",["schema_version","record_id","assignments","counts"]),
 (65,"validation/val001/VAL_001_SCHEMA_PROVENANCE_TRANSITION_MATRIX.json","SCHEMA_PROVENANCE_TRANSITION_MATRIX","espresso.val001.schema_provenance_transition_matrix.v1",["schema_version","record_id","prior_inferred_family_count","transition_count","entries","final_disposition"]),
 (66,"validation/val001/VAL_001_SCHEMA_TAXONOMY_AND_COUNTING_SPECIFICATION.json","SCHEMA_TAXONOMY_COUNTING","espresso.val001.schema_taxonomy_counting.v1",["schema_version","record_id","definitions","count_formulas","val001_schema_spec_015_disposition","counts"]),
 (67,"validation/val001/VAL_001_MUTATION_EXECUTION_COVERAGE.json","MUTATION_EXECUTION_COVERAGE","espresso.val001.mutation_execution_coverage.v1",["schema_version","record_id","declared_mutation_ids","executed_mutation_ids","missing_ids","unexpected_ids","duplicate_ids","placeholder_ids","category_counts","declared_count","executed_count","immutable_hash_checking_disabled_for_all_structural_and_semantic_tests","final_status"]),
 (68,"validation/val001/corrections/VAL_001_PR38_SCHEMA_PROVENANCE_AND_SEMANTIC_ENFORCEMENT_PLAN.json","CORRECTION_PLAN","espresso.val001.schema_provenance_semantic_enforcement_plan.v1",["schema_version","record_id","controlling_adjudication","starting_head","starting_tree","change_declaration","blocking_findings","nonblocking_finding","design","prohibited_actions","intended_commit_sequence","stop_conditions"]),
 (69,"validation/val001/contracts/VAL_001_SCHEMA_PROVENANCE_AND_SEMANTIC_COMPLETION_FREEZE.json","SCHEMA_PROVENANCE_COMPLETION_FREEZE","espresso.val001.schema_provenance_semantic_completion_freeze.v1",["schema_version","record_id","status","implementation","bindings","computed_counts","preserved_lineage","puckworks_lock","execution","claim_boundaries"]),
]

def primitive(key):
 if key.endswith("_count") or key.endswith("count"):return {"type":"integer","minimum":0}
 if key.startswith("is_") or key.endswith("_disabled_for_all_structural_and_semantic_tests"):return {"type":"boolean"}
 if key in {"allowed_origins","prohibited_origins","contracts","record_bindings","assignments","entries","declared_mutation_ids","executed_mutation_ids","missing_ids","unexpected_ids","duplicate_ids","placeholder_ids","blocking_findings","prohibited_actions","intended_additive_commit_sequence","intended_commit_sequence","stop_conditions"}:return {"type":"array","items":{},"uniqueItems":key.endswith("_ids") or key.endswith("_origins")}
 if key in {"counts","category_counts","computed_counts","definitions","count_formulas","authority","starting_identity","implementation","preserved_lineage","puckworks_lock","execution","claim_boundaries","design","designs"}:return {"type":"object"}
 if key=="bindings":return {"type":"array","items":{}}
 return {"type":"string"}

def closed(keys,overrides=None):
 overrides=overrides or {};return {"type":"object","required":keys,"properties":{k:overrides.get(k,primitive(k)) for k in keys},"additionalProperties":False}

def declared_schema(cls,keys):
 if cls=="SCHEMA_PROVENANCE_TRANSITION_MATRIX":
  entry_keys=["previous_inferred_schema_id","previous_schema_sha256","new_normative_contract_id","new_contract_sha256","new_governing_schema_id","new_governing_schema_sha256","authoritative_source_references","schema_bytes_identical","independent_derivation_explanation","no_instance_generation_test_id","semantic_profile_id","reviewer_disposition"]
  item=closed(entry_keys,{"previous_schema_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"new_contract_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"new_governing_schema_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"authoritative_source_references":{"type":"array","items":{"type":"string"},"minItems":1,"uniqueItems":True},"schema_bytes_identical":{"type":"boolean"},"reviewer_disposition":{"type":"string","const":"NORMATIVE_SOURCE_REPLACED"},"semantic_profile_id":{"type":"string","pattern":"^PROFILE-.+$"}})
  return closed(keys,{"prior_inferred_family_count":{"type":"integer","const":48},"transition_count":{"type":"integer","const":48},"entries":{"type":"array","items":item,"minItems":48,"maxItems":48},"final_disposition":{"type":"string","const":"ALL_PRIOR_INFERRED_FAMILIES_HAVE_NORMATIVE_TRANSITIONS"}})
 if cls=="SCHEMA_TAXONOMY_COUNTING":
  defkeys=["normative_schema_specification","governing_schema_family","administrative_meta_schema_family","schema_document_count","normative_contract_count","semantic_profile_count"]
  formulakeys=["governing_schema_family_count","prohibited_arithmetic","all_counts"]
  countkeys=["current_normative_specifications","current_referenced_specifications","current_unreferenced_specifications","governing_schema_families","schema_documents","administrative_meta_schema_families","schema_assignments"]
  assignment=closed(["schema_id","record_count"],{"record_count":{"type":"integer","minimum":1}})
  counts=closed(countkeys,{**{k:{"type":"integer","minimum":0} for k in countkeys[:-1]},"schema_assignments":{"type":"array","items":assignment,"minItems":1}})
  return closed(keys,{"definitions":closed(defkeys,{k:{"type":"string"} for k in defkeys}),"count_formulas":closed(formulakeys,{k:{"type":"string"} for k in formulakeys}),"val001_schema_spec_015_disposition":{"type":"string","enum":["OBSOLETE_REMOVED"]},"counts":counts})
 return closed(keys)

def mutation_inventory_schema():
 keys=["mutation_id","category","target_path_or_fixture_id","target_record_class","target_schema_id","target_normative_contract_id","target_semantic_profile_id","json_pointer","original_value","mutated_value","mutation_operation","precondition","expected_validation_layer","expected_invariant_id","expected_error_code","test_module","test_method_or_generated_test_id","immutable_hash_checking_disabled","expected_source_open_status","expected_scoring_status","execution_status"]
 props={k:{} for k in keys};props.update({"mutation_id":{"type":"string","pattern":"^MUT-.+$"},"category":{"type":"string","enum":["STRUCTURAL_SCHEMA","SCHEMA_DOCUMENT","SEMANTIC_PROFILE","ADMINISTRATIVE_ROOT_GRAPH","FREEZE_LOCK"]},"target_path_or_fixture_id":{"type":"string"},"target_record_class":{"type":"string"},"target_schema_id":{"type":"string"},"target_normative_contract_id":{"type":"string"},"target_semantic_profile_id":{"type":"string","pattern":"^PROFILE-.+$"},"json_pointer":{"type":"string"},"mutation_operation":{"type":"string"},"precondition":{"type":"string","const":"SYNTHETIC_BASELINE_VALID"},"expected_validation_layer":{"type":"string"},"expected_invariant_id":{"type":"string"},"expected_error_code":{"type":"string"},"test_module":{"type":"string"},"test_method_or_generated_test_id":{"type":"string"},"immutable_hash_checking_disabled":{"type":"boolean","const":True},"expected_source_open_status":{"type":"string","const":"NOT_OPENED"},"expected_scoring_status":{"type":"string","const":"NOT_INVOKED"},"execution_status":{"type":"string","const":"EXECUTED_SYNTHETICALLY"}})
 item=closed(keys,props);top=["schema_version","record_id","mutations","category_counts","total","count_source","scalar_baseline_counts_prohibited","placeholder_values_prohibited"]
 return closed(top,{"schema_version":{"type":"string","const":"espresso.val001.explicit_mutation_inventory.v2"},"record_id":{"type":"string","const":"VAL001-EXPLICIT-MUTATION-INVENTORY-2"},"mutations":{"type":"array","items":item,"minItems":1},"category_counts":{"type":"object"},"total":{"type":"integer","minimum":1},"count_source":{"type":"string","const":"LEN_OF_MUTATIONS_ARRAY_ONLY"},"scalar_baseline_counts_prohibited":{"type":"boolean","const":True},"placeholder_values_prohibited":{"type":"boolean","const":True}})

def explicit_registry_schema():
 spec_keys=["specification_id","normative_contract_id","origin","record_class","record_version","schema","schema_id","schema_path","schema_version","scope","semantic_profile_id"]
 spec=closed(spec_keys,{"specification_id":{"type":"string","pattern":"^VAL001-SCHEMA-SPEC-.+$"},"normative_contract_id":{"type":"string"},"origin":{"type":"string","enum":["NORMATIVE_CLASS_CONTRACT","NORMATIVE_VERSION_CONTRACT","NORMATIVE_RECORD_CONTRACT"]},"record_class":{"type":"string"},"record_version":{"type":"string"},"schema":{"type":"object"},"schema_id":{"type":"string"},"schema_path":{"type":"string","const":"validation/val001/VAL_001_NORMATIVE_SCHEMA_CONTRACT_REGISTRY.json"},"schema_version":{"type":"string"},"scope":{"type":"string"},"semantic_profile_id":{"type":"string","pattern":"^PROFILE-.+$"}})
 binding_keys=["path","specification_id","semantic_profile_id","record_class","current","audit_only","treatment"]
 binding_props={"path":{"type":"string"},"specification_id":{"type":"string","pattern":"^VAL001-SCHEMA-SPEC-.+$"},"semantic_profile_id":{"type":"string","pattern":"^PROFILE-.+$"},"record_class":{"type":"string"},"record_version":{"type":"string"},"current":{"type":"boolean"},"historical":{"type":"boolean"},"audit_only":{"type":"boolean"},"governing":{"type":"boolean"},"executable":{"type":"boolean"},"treatment":{"type":"string"},"schema_id":{"type":"string"},"schema_version":{"type":"string"}}
 binding={"type":"object","required":binding_keys,"properties":binding_props,"additionalProperties":False}
 countkeys=["current_normative_specifications","current_referenced_specifications","current_unreferenced_specifications","instance_inferred_governing_schemas","copied_inferred_governing_schemas","structural_signature_governing_schemas","filename_selected_governing_schemas"]
 return closed(["schema_version","record_id","allowed_origins","prohibited_origins","specifications","record_bindings","counts"],{"schema_version":{"type":"string","const":"espresso.val001.explicit_schema_specification_registry.v2"},"record_id":{"type":"string","const":"VAL001-EXPLICIT-SCHEMA-SPECIFICATION-REGISTRY-2"},"allowed_origins":{"type":"array","const":["NORMATIVE_CLASS_CONTRACT","NORMATIVE_RECORD_CONTRACT","NORMATIVE_VERSION_CONTRACT"]},"prohibited_origins":{"type":"array","const":["INSTANCE_INFERENCE","STRUCTURAL_SIGNATURE_INFERENCE","FILENAME_INFERENCE","COPIED_INFERRED_SCHEMA_WITH_RELABELLED_ORIGIN"]},"specifications":{"type":"array","items":spec,"minItems":1},"record_bindings":{"type":"array","items":binding,"minItems":1},"counts":closed(countkeys,{k:{"type":"integer","minimum":0} for k in countkeys})})

def consumed_lock_schema():
 keys=["alternate_activation_allowed","alternate_authority_allowed","alternate_invocation_id_allowed","alternate_ledger_allowed","authority_status","bindings","branch","claim_boundaries","freeze_binding","further_retry_authorized","issue","puckworks_lock","pull_request","record_id","remaining_governed_result_producing_invocations","remaining_real_data_comparison_invocations","schema_version","task"]
 false_keys=["alternate_activation_allowed","alternate_authority_allowed","alternate_invocation_id_allowed","alternate_ledger_allowed","further_retry_authorized"]
 props={k:{"type":"boolean","const":False} for k in false_keys};props.update({"authority_status":{"type":"string","const":"CONSUMED"},"bindings":{"type":"array","items":closed(["path","sha256"],{"path":{"type":"string"},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"}}),"minItems":1},"branch":{"type":"string","const":"validation/val-001-source-adapters"},"claim_boundaries":{"type":"object"},"freeze_binding":closed(["commit","path","sha256","tree"],{"commit":{"type":"string","pattern":"^[0-9a-f]{40}$"},"path":{"type":"string"},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"tree":{"type":"string","pattern":"^[0-9a-f]{40}$"}}),"issue":{"type":"integer","const":37},"puckworks_lock":closed(["commit","tree"],{"commit":{"type":"string","const":"fc61c4670ec7bf801e40bb391aab16048b8da26b"},"tree":{"type":"string","const":"1d553e44ee2f7480a5df521560801b478618cc84"}}),"pull_request":{"type":"integer","const":38},"record_id":{"type":"string"},"remaining_governed_result_producing_invocations":{"type":"integer","const":0},"remaining_real_data_comparison_invocations":{"type":"integer","const":0},"schema_version":{"type":"string","enum":["espresso.val001.postresult_execution_lock.v2","espresso.val001.postresult_execution_lock.v3"]},"task":{"type":"string","const":"VAL-001"}})
 return closed(keys,props)

def main():
 ap=argparse.ArgumentParser();ap.add_argument("--root",required=True);a=ap.parse_args();root=Path(a.root).resolve();reg=load_json(root/NORMATIVE_REGISTRY);assign=load_json(root/ASSIGNMENT_REGISTRY);profiles=load_json(root/"validation/val001/VAL_001_SEMANTIC_PROFILE_REGISTRY.json")
 mutation_contract=next(c for c in reg["contracts"] if c["specification_id"]=="VAL001-SCHEMA-SPEC-061")
 mutation_contract["schema_version"]="espresso.val001.explicit_mutation_inventory.v2";mutation_contract["record_version"]="espresso.val001.explicit_mutation_inventory.v2";mutation_contract["governing_schema"]=mutation_inventory_schema();mutation_contract["required_fields"]=mutation_contract["governing_schema"]["required"]
 for collection in (reg["record_bindings"],assign["assignments"]):
  target=next(x for x in collection if x["path"]=="validation/val001/VAL_001_EXPLICIT_MUTATION_INVENTORY.json");target["record_version"]="espresso.val001.explicit_mutation_inventory.v2";target["schema_version"]="espresso.val001.explicit_mutation_inventory.v2"
 explicit_contract=next(c for c in reg["contracts"] if c["specification_id"]=="VAL001-SCHEMA-SPEC-059");explicit_contract["schema_version"]="espresso.val001.explicit_schema_specification_registry.v2";explicit_contract["record_version"]="espresso.val001.explicit_schema_specification_registry.v2";explicit_contract["governing_schema"]=explicit_registry_schema();explicit_contract["required_fields"]=explicit_contract["governing_schema"]["required"]
 for collection in (reg["record_bindings"],assign["assignments"]):
  target=next(x for x in collection if x["path"]=="validation/val001/VAL_001_EXPLICIT_SCHEMA_SPECIFICATION_REGISTRY.json");target["record_version"]="espresso.val001.explicit_schema_specification_registry.v2";target["schema_version"]="espresso.val001.explicit_schema_specification_registry.v2"
 lock_contract=next(c for c in reg["contracts"] if c["specification_id"]=="VAL001-SCHEMA-SPEC-029");lock_contract["governing_schema"]=consumed_lock_schema();lock_contract["required_fields"]=lock_contract["governing_schema"]["required"]
 def replace_origin(node):
  if isinstance(node,dict):
   if isinstance(node.get("enum"),list) and set(node["enum"])=={"EXPLICIT_CLASS_SEMANTICS","EXPLICIT_VERSION_SEMANTICS","EXPLICIT_RECORD_SEMANTICS"}:node["enum"]=["NORMATIVE_CLASS_CONTRACT","NORMATIVE_VERSION_CONTRACT","NORMATIVE_RECORD_CONTRACT"]
   for value in node.values():replace_origin(value)
  elif isinstance(node,list):
   for value in node:replace_origin(value)
 for contract in reg["contracts"]:replace_origin(contract["governing_schema"])
 reg["contracts"]=[c for c in reg["contracts"] if c["specification_id"] not in {f"VAL001-SCHEMA-SPEC-{n:03d}" for n,*_ in DECLARATIONS}]
 reg["record_bindings"]=[b for b in reg["record_bindings"] if b["path"] not in {p for _,p,*_ in DECLARATIONS}]
 assign["assignments"]=[x for x in assign["assignments"] if x["path"] not in {p for _,p,*_ in DECLARATIONS}]
 profile=next(x for x in profiles["profiles"] if x["profile_id"]=="PROFILE-CURRENT-GOVERNANCE")
 for n,path,cls,version,keys in DECLARATIONS:
  spec=f"VAL001-SCHEMA-SPEC-{n:03d}";contract=f"VAL001-NORMATIVE-CONTRACT-{n:03d}";schema_id=f"{cls.lower()}.v1"
  schema={"$schema":"https://json-schema.org/draft/2020-12/schema","title":f"Normative {cls} contract","description":"Explicit record-level administrative contract; deeper normative invariants execute in the named validators.",**declared_schema(cls,keys)}
  reg["contracts"].append({"normative_contract_id":contract,"version":"v1","specification_id":spec,"schema_id":schema_id,"schema_version":version,"record_class":cls,"record_version":version,"status":"CURRENT","scope":"EXPLICIT_RECORD_SEMANTICS","origin":"NORMATIVE_RECORD_CONTRACT","authoritative_source_references":["human-owner correction authority dated 2026-08-01","docs/validation/VAL_001_SOURCE_ADAPTERS_AND_COMPONENT_COMPARISONS.md"],"required_fields":keys,"optional_fields":[],"prohibited_fields":[],"null_and_unavailable_reason_semantics":"NULL_ONLY_WHERE_SCHEMA_PERMITS; unavailable values require explicit reason fields","allowed_enum_domain":"DECLARED_BY_NORMATIVE_CONTRACT_AND_INVARIANTS","prohibited_enum_values":["INSTANCE_INFERENCE","CURRENT_VALIDATION","PHYSICAL_VALIDATION_ESTABLISHED"],"execution_status":"NONEXECUTABLE_ADMINISTRATION","governing_audit_status":"CURRENT_GOVERNING_ADMINISTRATION","protected_holdout_status":"NO_ACCESS_OR_SCORING_AUTHORIZED","rights_requirements":"NO_RIGHTS_ESCALATION","fitting_retuning_restrictions":"PROHIBITED","solver_configuration_restrictions":"PROHIBITED","dependency_lock_requirements":"PUCKWORKS_EXACT_IF_APPLICABLE","evidence_role_restrictions":"ADMINISTRATIVE_ONLY","score_bearing_rules":"NON_SCORE_BEARING","claim_ceiling":"NO_PHYSICAL_VALIDATION_OR_NEW_PHYSICS","physical_validation_status":"NOT_ESTABLISHED","identifiability_status":"NOT_APPLICABLE","campaign_status":"NOT_APPLICABLE","semantic_profile_id":"PROFILE-CURRENT-GOVERNANCE","required_cross_record_bindings":[],"required_mutation_ids":[f"MUT-STRUCTURAL-{3*(len(reg['contracts']))+i:03d}" for i in range(1,4)],"governing_schema":schema})
  binding={"path":path,"specification_id":spec,"semantic_profile_id":"PROFILE-CURRENT-GOVERNANCE","record_class":cls,"record_version":version,"schema_id":schema_id,"schema_version":version,"current":True,"audit_only":False,"executable":False,"treatment":"CURRENT_DEEP_SCHEMA"}
  reg["record_bindings"].append(binding);assign["assignments"].append({**binding,"normative_contract_id":contract,"current":True,"historical":False,"audit_only":False,"governing":True,"executable":False,"treatment":"CURRENT_DEEP_SCHEMA"})
  if spec not in profile["applies_to_specification_ids"]:profile["applies_to_specification_ids"].append(spec)
 historical_lock="validation/val001/contracts/historical/VAL_001_POSTRESULT_EXECUTION_LOCK_V4.json"
 reg["record_bindings"]=[b for b in reg["record_bindings"] if b["path"]!=historical_lock];assign["assignments"]=[x for x in assign["assignments"] if x["path"]!=historical_lock]
 lock_contract=next(c for c in reg["contracts"] if c["specification_id"]=="VAL001-SCHEMA-SPEC-029")
 historical_binding={"path":historical_lock,"specification_id":"VAL001-SCHEMA-SPEC-029","semantic_profile_id":"PROFILE-HISTORICAL-AUDIT","record_class":"EXECUTION_LOCK","record_version":"espresso.val001.postresult_execution_lock.v2","current":False,"audit_only":True,"executable":False,"treatment":"IMMUTABLE_HISTORICAL_DEEP_SCHEMA"}
 reg["record_bindings"].append(historical_binding);assign["assignments"].append({**historical_binding,"normative_contract_id":lock_contract["normative_contract_id"],"schema_id":lock_contract["schema_id"],"schema_version":lock_contract["schema_version"],"historical":True,"governing":False})
 historical_profile=next(x for x in profiles["profiles"] if x["profile_id"]=="PROFILE-HISTORICAL-AUDIT")
 if "VAL001-SCHEMA-SPEC-029" not in historical_profile["applies_to_specification_ids"]:historical_profile["applies_to_specification_ids"].append("VAL001-SCHEMA-SPEC-029")
 reg["contracts"].sort(key=lambda x:x["specification_id"]);reg["record_bindings"].sort(key=lambda x:x["path"]);assign["assignments"].sort(key=lambda x:x["path"]);profile["applies_to_specification_ids"].sort();historical_profile["applies_to_specification_ids"].sort()
 reg["counts"]={"current_normative_contracts":len(reg["contracts"]),"current_referenced_contracts":len({x["specification_id"] for x in reg["record_bindings"]}),"current_unreferenced_contracts":0,"instance_inferred_governing_schemas":0,"copied_inferred_governing_schemas":0,"structural_signature_governing_schemas":0,"filename_selected_governing_schemas":0}
 assign["counts"]={"governed_records":len(assign["assignments"]),"records_without_assignment":0,"duplicate_assignments":0}
 (root/NORMATIVE_REGISTRY).write_bytes(canonical_json(reg));(root/ASSIGNMENT_REGISTRY).write_bytes(canonical_json(assign));(root/"validation/val001/VAL_001_SEMANTIC_PROFILE_REGISTRY.json").write_bytes(canonical_json(profiles))
if __name__=="__main__":main()
