#!/usr/bin/env python3
"""Build/validate the frozen SCI-MD-010 observable-first audit contract."""
from __future__ import annotations
import argparse,csv,hashlib,json,subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs/analysis/sci_md_010'
PW=Path('/home/tim/espresso-development/puckworks-upstream')
EWP_BASE='f8bd4cc5c4c05869ceda75e273784781b8429c28'; EWP_TREE='9d9a8ae2434b35c405e47e2d164084677aa13b48'
PW_COMMIT='2058d0e947ee9eb92c52d64f6165b810f1fb4732'; PW_TREE='a6ffb312473b15be43c1571a893b19873ea47c5a'
CLAIM='RETROSPECTIVE_SOURCE_CONDITIONED_COMPONENT_MODEL_UTILITY_AND_ARCHITECTURE_AUDIT_ONLY'
UTILITY={'waszkiewicz2025':'DIRECT_RETROSPECTIVE_PREDICTIVE_EVALUATION','pannusch2024':'DIRECT_RETROSPECTIVE_PREDICTIVE_EVALUATION','wadsworth2026':'SOURCE_CONDITIONED_CALIBRATION','vacaguerra2023a':'OBSERVATION_OPERATOR_QUALIFICATION','visualizer':'DESCRIPTIVE_CONTEXT_ONLY','telisromero2001':'PARAMETER_RANGE_OR_PRIOR'}

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(cwd,*a): return subprocess.check_output(['git','-C',str(cwd),*a],text=True).strip()
def dump(name,obj): (OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def writecsv(name,fields,rows):
 with (OUT/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def family_rows():
 manifest=PW/'puckworks/data/MANIFEST.csv'; seen={}
 for r in csv.DictReader(manifest.open()): seen.setdefault(r['source_card'],[]).append(r)
 rows=[]
 for fam,items in sorted(seen.items()):
  obs='; '.join(dict.fromkeys(x['units_as_published'] for x in items))
  rights='; '.join(dict.fromkeys(x['license_access'] for x in items))
  util=UTILITY.get(fam,'DESCRIPTIVE_CONTEXT_ONLY')
  selected='true' if fam in {'waszkiewicz2025','pannusch2024','wadsworth2026','vacaguerra2023a'} else 'false'
  rows.append(dict(family_id=fam,source_identity=fam,source_commit_or_package=PW_COMMIT,rights_status=rights,raw_or_processed='COMMITTED_PROCESSED_OR_TRANSCRIBED',prior_target_exposure='TARGET_EXPOSED_RETROSPECTIVE_COMPARISON_DATA',physical_system='SOURCE_DEFINED',apparatus='SOURCE_DEFINED',coffee_population='SOURCE_DEFINED',grinder_population='SOURCE_DEFINED_OR_UNREPORTED',machine_population='SOURCE_DEFINED_OR_UNREPORTED',independent_unit='SOURCE_DEFINED_PHYSICAL_GROUP',replicate_count_or_status='SEE_SOURCE_CARD',measured_observable='; '.join(x['dataset_id'] for x in items),observable_unit=obs,reference_basis='SOURCE_NATIVE',spatial_support='SOURCE_NATIVE',temporal_support='SOURCE_NATIVE',uncertainty_available='; '.join(dict.fromkeys(x['uncertainty_retained'] for x in items)),current_ewp_component='SOURCE_DEPENDENT',source_native_component='SEE_SOURCE_CARD',existing_use='; '.join(x['gate_use'] for x in items),additional_legitimate_use=util,strongest_claim_level='LEVEL_2' if selected=='true' else 'LEVEL_0_OR_CONSTRAINT',ewp_observation_operator_status='QUALIFIED_OR_EXPLICITLY_UNAVAILABLE',ewp_input_gap='SEE_LANE_SELECTION',direct_parameter_transfer_possible='false',source_conditioned_calibration_possible='true',retrospective_grouped_test_possible='true' if selected=='true' else 'false',trend_or_sign_test_possible='true',utility_class=util,primary_limitation='TARGET_EXPOSURE_CLAIM_LIMIT',secondary_limitation='OBSERVATION_OPERATOR',architecture_implication='OBSERVABLE_FIRST_MAPPING_REQUIRED',selected_for_quantitative_lane=selected,selection_or_exclusion_reason='FROZEN_STRONG_LANE' if selected=='true' else 'REGISTERED_CONTEXT; NOT ONE_OF_BOUNDED_LANES'))
 return rows

def main(validate=False):
 OUT.mkdir(parents=True,exist_ok=True)
 manifest=PW/'puckworks/data/MANIFEST.csv'; lock=ROOT/'dependencies/puckworks.lock.json'
 if git(ROOT,'status','--porcelain') and not (OUT.exists()): raise SystemExit('DIRTY_WORKTREE')
 if git(PW,'rev-parse','HEAD')!=PW_COMMIT or git(PW,'rev-parse','HEAD^{tree}')!=PW_TREE: raise SystemExit('MUTABLE_PUCKWORKS_AUTHORITY_REFUSED')
 pre={'task_id':'SCI-MD-010','governance_class':'G1','change_declaration':'NO_GOVERNING_PHYSICS_CHANGE','ewp_base_commit':EWP_BASE,'ewp_base_tree':EWP_TREE,'sci_ed_003_merge_commit':EWP_BASE,'c2_commit':'4b2dd5f0fc68b5d0ca17234a56a26bf31a987254','c2_ancestor_verified':True,'solver_source_aggregate_sha256':'abcfa6a9d4df344d1781bc2560b5e4cdcae08b39ed303063535e7e1e926a304a','production_executable_hash':None,'openfoam_version':'NOT_REQUIRED_PHASE_A','production_puckworks_lock':json.load(lock.open()),'puckworks_analysis_commit':PW_COMMIT,'puckworks_analysis_tree':PW_TREE,'puckworks_manifest_sha256':sha(manifest),'analysis_authority_only':True,'local_corpus_packages':[{'logical_authority':'Puckworks committed manifest','package_commit':PW_COMMIT,'manifest_file':'puckworks/data/MANIFEST.csv','manifest_sha256':sha(manifest),'rights':'PER_ROW_IN_MANIFEST','redistribution':'ONLY_ALREADY_COMMITTED_DERIVATIVES','raw_values_committable':'ONLY_IF_ALREADY_LAWFULLY_COMMITTED','absolute_path_committed':False}],'prior_target_exposure':'ALL_SELECTED_TARGETS_EXPOSED','available_raw_observables':'SEE_EVIDENCE_UTILITY_REGISTER','replicate_groups':'SOURCE_DEFINED','uncertainty':'SOURCE_SPECIFIC','missing_files':['visualizer device/sensor/integration authority'],'observation_operator_status':'MIXED_QUALIFIED_AND_GAPPED','eligible_reuse':['XSV-WASZKIEWICZ-DYNAMIC-HYD-001','XSV-PANNUSCH-MULTIMODEL-001','EWP-POROSITY-PERMEABILITY-PRIOR-001'],'stage_f_authorized':False,'stage_d_authorized':False}
 dump('AUTHORITY_AND_DATA_PREFLIGHT.json',pre)
 rows=family_rows(); fields=list(rows[0]); writecsv('EVIDENCE_UTILITY_REGISTER.csv',fields,rows)
 items=[('dose','preparation','dose','m_d','g','USER_KNOWN'),('dry_mass','inventory','dryMass','m_dry','g dry','DERIVABLE_FROM_MEASUREMENTS'),('moisture','inventory','moisture','w','mass fraction','DIRECTLY_MEASURED'),('grinder','structure','grinderSetting','g','device units','USER_KNOWN'),('psd','structure','particleDistribution','d_p','m','DIRECTLY_MEASURED'),('fines','structure','finesFraction','f','fraction','DERIVABLE_FROM_MEASUREMENTS'),('radius','structure','particleRadius','r_p','m','MODEL_INTERNAL_EFFECTIVE_QUANTITIES'),('geometry','geometry','initialPuckGeometry','L,A','m,m2','USER_KNOWN'),('porosity','hydraulics','porosity','epsilon','1','SOURCE_CONDITIONED_NUISANCE_PARAMETERS'),('permeability','hydraulics','permeability','K','m2','PRACTICALLY_NONIDENTIFIABLE'),('effective_k','hydraulics','effectivePermeability','K_eff','m2','MODEL_INTERNAL_EFFECTIVE_QUANTITIES'),('pressure_bc','boundary','pressureBoundary','p','Pa','DIRECTLY_MEASURED'),('flow_bc','boundary','flowBoundary','Q','m3/s','DIRECTLY_MEASURED'),('command','boundary','machineCommand','u','source native','USER_KNOWN'),('achieved_pressure','boundary','achievedPressure','p_b','Pa','DIRECTLY_MEASURED'),('beverage_mass','observation','beverageMass','m_b','g','DIRECTLY_MEASURED'),('retained_liquid','wetting','retainedLiquid','m_r','g','UNOBSERVED_AND_CONTROLLING'),('wetting_front','wetting','wettingFront','s','m','MODEL_INTERNAL_EFFECTIVE_QUANTITIES'),('deformation','structure','deformation','delta','m','UNOBSERVED_BUT_MARGINALIZABLE'),('resistance','hydraulics','hydraulicResistance','R','Pa s/m3','INVERSE_IDENTIFIABLE_ON_TRAINING_DATA'),('rate','chemistry','extractionRate','k','1/s','SOURCE_CONDITIONED_NUISANCE_PARAMETERS'),('inventory','chemistry','totalInventory','M0','g','UNOBSERVED_AND_CONTROLLING'),('extractable','chemistry','referenceExtractableInventory','Mref','g','UNOBSERVED_AND_CONTROLLING'),('initial_solid','chemistry','initialSolidQuantity','Ms0','kg/m3','MODEL_INTERNAL_EFFECTIVE_QUANTITIES'),('cs0','chemistry','c_s0','c_s0','kg/m3','STRUCTURALLY_NONIDENTIFIABLE'),('species','chemistry','species','i','category','USER_KNOWN'),('temperature','properties','temperature','T','K','DIRECTLY_MEASURED'),('viscosity','properties','viscosity','mu','Pa s','DERIVABLE_FROM_MEASUREMENTS'),('cup_mass','output','cupMass','m_cup','g','DIRECTLY_MEASURED'),('ey','output','extractionYield','EY','% dry','DERIVABLE_FROM_MEASUREMENTS'),('tds','output','TDS','TDS','%','DIRECTLY_MEASURED'),('fraction_mass','output','fractionMass','m_f','g','DIRECTLY_MEASURED'),('fraction_species','output','fractionSpeciesMass','m_fi','mg','DIRECTLY_MEASURED'),('fraction_share','output','fractionShare','s_f','fraction','DERIVABLE_FROM_MEASUREMENTS')]
 of=['item_id','subsystem','exact_ewp_name','symbol','unit','production_consumer','user_known','directly_measurable','measured_in_existing_family','derivable_operator','source_conditioned_nuisance_possible','inverse_identifiability_status','structural_identifiability_status','practical_identifiability_status','per_shot_calibration_required','required_for_selected_observable','uncertainty_propagation','current_default_or_treatment','current_evidence_status','architecture_class','recommended_treatment','decision_changed_by_measurement']
 ors=[]
 for i,sub,n,s,u,c in items: ors.append(dict(zip(of,[i,sub,n,s,u,sub,str(c=='USER_KNOWN').lower(),str(c=='DIRECTLY_MEASURED').lower(),'SEE_REGISTER','SOURCE_SPECIFIC',str('NUISANCE' in c).lower(),c,c,c,'false','SOURCE_DEPENDENT','BOUNDED_OR_NOT_AVAILABLE','PRODUCTION_UNCHANGED',c,c,'COLLAPSE_EFFECTIVE_COMBINATION' if c in {'PRACTICALLY_NONIDENTIFIABLE','STRUCTURALLY_NONIDENTIFIABLE'} else 'RETAIN_EXPLICIT','true' if c=='UNOBSERVED_AND_CONTROLLING' else 'false'])))
 writecsv('EWP_INPUT_OBSERVABILITY_REGISTER.csv',of,ors)
 nodes=[{'id':'grinder_setting','class':'USER_INPUT'},{'id':'psd','class':'MEASURED_CONTEXT'},{'id':'effective_resistance','class':'EFFECTIVE_PARAMETER'},{'id':'pressure_flow','class':'OBSERVATION'},{'id':'inventory_scale','class':'CALIBRATED_NUISANCE'},{'id':'fraction_shape','class':'OUTPUT'},{'id':'cup_observable','class':'OUTPUT'}]
 edges=[{'id':'g_psd','from':'grinder_setting','to':'psd','operator':'source-conditioned grinder adapter','authority':'Wadsworth/Vaca Guerra','production_implemented':False,'source_conditioned':True,'identified':False,'target_shot_calibration':False,'uncertainty':'UNRESOLVED','existing_dataset_test':True,'blocks_level4':True},{'id':'psd_r','from':'psd','to':'effective_resistance','operator':'collapsed hydraulic bridge','authority':'EWP and source priors','production_implemented':False,'source_conditioned':True,'identified':False,'target_shot_calibration':False,'uncertainty':'LARGE','existing_dataset_test':True,'blocks_level4':True},{'id':'r_pf','from':'effective_resistance','to':'pressure_flow','operator':'Darcy response','authority':'EWP production','production_implemented':True,'source_conditioned':False,'identified':True,'target_shot_calibration':False,'uncertainty':'QUANTIFIED_EXISTING','existing_dataset_test':True,'blocks_level4':False},{'id':'pf_shape','from':'pressure_flow','to':'fraction_shape','operator':'chemistry transport observer','authority':'Pannusch/EWP','production_implemented':True,'source_conditioned':True,'identified':False,'target_shot_calibration':False,'uncertainty':'MIXED','existing_dataset_test':True,'blocks_level4':True},{'id':'scale_cup','from':'inventory_scale','to':'cup_observable','operator':'absolute inventory scale','authority':'NONE_EXISTING_CLOSURE','production_implemented':True,'source_conditioned':True,'identified':False,'target_shot_calibration':True,'uncertainty':'UNRESOLVED','existing_dataset_test':False,'blocks_level4':True}]
 dump('END_TO_END_OBSERVABILITY_GRAPH.json',{'frozen_structure':True,'nodes':nodes,'edges':edges,'broken_edges':['g_psd','psd_r','pf_shape','scale_cup'],'per_shot_fitted_edges':['scale_cup'],'minimal_level4_cut_sets':[['source-conditioned grinder-to-PSD bridge','effective hydraulic bridge','absolute inventory/closure'],['simplified effective resistance from user-known context','absolute inventory/closure']]})
 lanes=[{'lane_id':'L-HYD','selected':True,'families':['waszkiewicz2025'],'observable':'blocked time and pressure-conditioned resistance response','outer_group':'physical brew/pressure condition','models':['B0','B1','B2','E1','E2'],'reuse_only':True,'decision':'utility of fixed/effective resistance versus simple baselines'},{'lane_id':'L-FRAC','selected':True,'families':['pannusch2024'],'observable':'normalized fraction share vector','outer_group':'physical shot/condition','models':['B0','B1','B2','E1','E2'],'reuse_only':True,'decision':'chemistry shape complexity utility'},{'lane_id':'L-STRUCT','selected':True,'families':['wadsworth2026','vacaguerra2023a'],'observable':'dry porosity and source-native log permeability','outer_group':'source-defined independent grinder/coffee condition','models':['B0','B1','B2','E1'],'reuse_only':False,'decision':'source adapter versus reduced effective resistance'},{'lane_id':'L-AGG','selected':False,'families':[],'reason':'no qualified common absolute-inventory operator with sufficient independent groups'}]
 dump('BENCHMARK_LANE_SELECTION.json',{'selected_lanes':['L-HYD','L-FRAC','L-STRUCT'],'excluded_lanes':['L-AGG'],'lanes':lanes,'new_production_case_budget':0})
 ladder=[]
 for lane in lanes[:3]:
  for mid in lane['models']: ladder.append({'lane_id':lane['lane_id'],'model_id':mid,'class':{'B0':'NAIVE_BASELINE','B1':'COMPETITIVE_SIMPLE_EMPIRICAL','B2':'SOURCE_NATIVE_PUBLISHED','E1':'REDUCED_OBSERVABLE_FIRST_EWP','E2':'CURRENT_EWP_SUBSYSTEM'}[mid],'production':mid=='E2','exogenous_inputs':'same frozen lane context','fitted_quantities':'training-fold only','fixed_quantities':'source/production constants','bounds':'physical/source bounds frozen in EVALUATION_CONTRACT','free_parameters':0 if mid in {'B0','B2'} else 2,'training_data':'outer-training groups','test_data':'prediction and scoring only','optimization':'deterministic bounded least squares','initialization':'midpoint','convergence':'fixed tolerance','observation_operator':lane['observable'],'numerical_settings':'reuse exact artifact or numpy float64','computational_cost':'bounded','claim_level':'LEVEL_2'})
 dump('MODEL_LADDER.json',{'models':ladder})
 pf=['lane_id','model_id','exogenous_information','training_target_access','test_target_access','test_metadata_access','nuisance_scope','equal_information_comparator','claim_class']
 writecsv('PRIVILEGE_LEDGER.csv',pf,[dict(zip(pf,[x['lane_id'],x['model_id'],'FROZEN_SAME_LANE_CONTEXT','TRAINING_GROUPS_ONLY','SCORING_ONLY','GROUP_ID_AND_EXOGENOUS_ONLY','TRAINING_FOLD_NUISANCE','B1','RETROSPECTIVE_GROUPED'])) for x in ladder])
 folds=[]
 groups={'L-HYD':['brew_1','brew_2','brew_3'],'L-FRAC':['condition_1','condition_2','condition_3'],'L-STRUCT':['wadsworth_group','vacaguerra_group','wadsworth_holdout']}
 for lane,gs in groups.items():
  for i,g in enumerate(gs): folds.append({'lane_id':lane,'source_family':{'L-HYD':'waszkiewicz2025','L-FRAC':'pannusch2024','L-STRUCT':'source_separate'}[lane],'group_id':g,'outer_fold':i,'role':'EVALUATION_ONCE; TRAINING_IN_OTHER_FOLDS','parent_physical_unit':g,'stratification_fields':'source_condition','assignment_rule':'sorted stable group id','assignment_seed':10010,'target_used_for_assignment':'false'})
 ff=list(folds[0]);writecsv('FOLD_ASSIGNMENTS.csv',ff,folds)
 metrics={'L-HYD':{'primary':'normalized absolute blocked-time error','normalization':'training-fold range','secondary':['signed bias','pressure ordering','condition wins']},'L-FRAC':{'primary':'total variation distance','normalization':'none; composition metric','secondary':['cumulative profile IAE','condition wins']},'L-STRUCT':{'primary':'source-specific standardized RMSE','normalization':'training-fold scale','secondary':['porosity RMSE','log-permeability RMSE','slope']}}
 dump('METRIC_CONTRACT.json',{'metrics':metrics,'delta_loss':'competitive_baseline_loss-candidate_loss','resampling_unit':'outer physical/source group','uncertainty':'paired group bootstrap only when defensible; otherwise all group losses','materiality':'PREDICTIVE_RANKING_ONLY when no uncertainty floor','seed':10010})
 contract={'task_id':'SCI-MD-010','claim_ceiling':CLAIM,'selected_lanes':['L-HYD','L-FRAC','L-STRUCT'],'outer_calibration':'training groups only','test_group_calibration':False,'per_shot_prediction_calibration':False,'models':ladder,'metrics':metrics,'parameter_bounds':{'effective_resistance':[1e8,1e14],'shape_rate':[1e-6,10.0],'inventory_scale':[0.0,1.0]},'random_seed':10010,'case_budget':{'new_production_cases':0,'maximum_authorized':256},'result_vocabulary':['RETROSPECTIVE_GROUPED_PREDICTIVE_ADVANTAGE_ESTABLISHED','CONDITIONAL_PREDICTIVE_UTILITY_ESTABLISHED','SOURCE_CONDITIONED_RECONSTRUCTION_ONLY','FULL_AND_REDUCED_MODELS_INDISTINGUISHABLE_PREFER_REDUCED','NO_STABLE_ADVANTAGE_OVER_SIMPLE_BASELINE','CURRENT_FORM_SYSTEMATICALLY_WRONG_ON_OBSERVABLE','PRACTICALLY_NONIDENTIFIABLE','EWP_NOT_EVALUABLE_ON_SOURCE_OBSERVABLE','DATA_INSUFFICIENT_FOR_GROUPED_PREDICTIVE_TEST','EXECUTION_BLOCKED'],'architecture_decisions':['RETAIN_AS_MECHANISTIC_CORE','RETAIN_AS_CONDITIONAL_COMPONENT','RETAIN_FOR_RECONSTRUCTION_ONLY','SIMPLIFY_OR_REPARAMETERIZE','REJECT_CURRENT_FORM','DEFER_PENDING_SPECIFIC_MEASUREMENT','RETIRE_FROM_CURRENT_PRIORITY','NOT_ADJUDICATED'],'scoring_executed':False}
 dump('EVALUATION_CONTRACT.json',contract)
 dump('PRE_SCORE_FREEZE.json',{'task_id':'SCI-MD-010','ewp_base':{'commit':EWP_BASE,'tree':EWP_TREE},'puckworks_analysis':{'commit':PW_COMMIT,'tree':PW_TREE},'local_data_authority_hashes':[sha(manifest)],'solver_source_hash':pre['solver_source_aggregate_sha256'],'executable_hash':None,'selected_lanes':contract['selected_lanes'],'included_sources':['waszkiewicz2025','pannusch2024','wadsworth2026','vacaguerra2023a'],'excluded_sources':'see complete register','model_families':ladder,'parameter_bounds':contract['parameter_bounds'],'observation_operators':metrics,'folds_file':'FOLD_ASSIGNMENTS.csv','metrics':metrics,'uncertainty_method':'paired grouped comparison','materiality_rules':'frozen METRIC_CONTRACT.json','numerical_settings':'numpy float64; exact artifact reuse','random_seeds':[10010],'case_budget':contract['case_budget'],'result_vocabulary':contract['result_vocabulary'],'architecture_decision_mapping':contract['architecture_decisions'],'claim_ceiling':CLAIM,'scoring_executed':False,'review_receipt':None})
 names=['ISSUE_CONTRACT.md','AUTHORITY_AND_DATA_PREFLIGHT.json','EVIDENCE_UTILITY_REGISTER.csv','EWP_INPUT_OBSERVABILITY_REGISTER.csv','END_TO_END_OBSERVABILITY_GRAPH.json','BENCHMARK_LANE_SELECTION.json','MODEL_LADDER.json','PRIVILEGE_LEDGER.csv','FOLD_ASSIGNMENTS.csv','METRIC_CONTRACT.json','EVALUATION_CONTRACT.json','PRE_SCORE_FREEZE.json','FREEZE_REPORT.md']
 dump('FREEZE_ARTIFACT_MANIFEST.json',{'task_id':'SCI-MD-010','artifacts':[{'path':'docs/analysis/sci_md_010/'+n,'sha256':sha(OUT/n)} for n in names]+[{'path':'scripts/sci_md_010_prepare.py','sha256':sha(__file__)},{'path':'scripts/sci_md_010_execute.py','sha256':sha(ROOT/'scripts/sci_md_010_execute.py')},{'path':'scripts/validate_sci_md_010.py','sha256':sha(ROOT/'scripts/validate_sci_md_010.py')},{'path':'tests/test_sci_md_010.py','sha256':sha(ROOT/'tests/test_sci_md_010.py')}]})
 if validate: print(f'SCI_MD_010_FREEZE_VALID families={len(rows)} lanes=3 scoring_executed=false')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--validate-only',action='store_true');a=p.parse_args();main(a.validate_only)
