#!/usr/bin/env python3
"""Generate or validate the correction-limited SCI-MD-011 R1 freeze."""
import argparse, hashlib, json, os
from pathlib import Path
from sci_md_011_core import *
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'docs/analysis/sci_md_011';S10=ROOT/'docs/analysis/sci_md_010'
PW_COMMIT='2058d0e947ee9eb92c52d64f6165b810f1fb4732';PW_TREE='a6ffb312473b15be43c1571a893b19873ea47c5a';R0='5c252033bcdd40d46dc4cc457e571aa729a8d1cc'
HANDOFF=['ANALYSIS_ROW_INDEX.csv','FOLD_ASSIGNMENTS.csv','FOLD_MEMBERSHIP.csv','BREW_RESULTS.csv','FOLD_RESULTS.csv','CONDITION_RESULTS.csv','AGGREGATE_RESULTS.csv','UNCERTAINTY_RESULTS.json','PRESSURE_RESPONSE_DIAGNOSTICS.json','PARAMETER_STABILITY.csv','METRIC_CONTRACT.json','MODEL_SPECIFICATIONS.json','INPUT_ARTIFACT_REGISTER.json','PRE_SCORE_FREEZE.json','FREEZE_ARTIFACT_MANIFEST.json','RESULT_ARTIFACT_MANIFEST.json']
PW_FILES=['docs/cards/waszkiewicz2025.md','puckworks/models/waszkiewicz2025/poroelastic.py','puckworks/data/MANIFEST.csv','puckworks/data/waszkiewicz2025/solids_calibration.csv','puckworks/data/waszkiewicz2025/constants.csv','puckworks/data/waszkiewicz2025/brewer_quadratic_params.csv','puckworks/data/waszkiewicz2025/equilibrium_windows.csv','puckworks/data/waszkiewicz2025/traces_per_brew.csv']
FREEZE_FILES=['docs/analysis/sci_md_011/TASK_CONTRACT.md','docs/analysis/sci_md_011/AUTHORITY_AND_HANDOFF.json','docs/analysis/sci_md_011/SCI_MD_010_HANDOFF.json','docs/analysis/sci_md_011/OBSERVATION_INTERFACE.json','docs/analysis/sci_md_011/EWP_CLOSURE_EQUIVALENCE.md','docs/analysis/sci_md_011/EWP_CLOSURE_EQUIVALENCE.json','docs/analysis/sci_md_011/MODEL_SPECIFICATIONS.json','docs/analysis/sci_md_011/PRIVILEGE_LEDGER.csv','docs/analysis/sci_md_011/EVALUATION_CONTRACT.json','docs/analysis/sci_md_011/PRE_SCORE_FREEZE.json','docs/analysis/sci_md_011/FREEZE_REPORT.md','docs/analysis/sci_md_011/CLOSURE_ORACLE_RESULTS.csv','docs/analysis/sci_md_011/CLOSURE_ORACLE_RECEIPT.json','scripts/sci_md_011_core.py','scripts/sci_md_011_prepare.py','scripts/sci_md_011_execute.py','scripts/validate_sci_md_011.py','scripts/run_sci_md_011_closure_oracle.sh','tests/test_sci_md_011.py','tests/fixtures/sci_md_011_synthetic_receipt.json','tests/fixtures/sci_md_011_closure_oracle/sci_md_011_closure_oracle.C','tests/fixtures/sci_md_011_closure_oracle/Make/files','tests/fixtures/sci_md_011_closure_oracle/Make/options']
def puckworks():
 raw=os.environ.get('SCI_MD_011_PUCKWORKS_ROOT','')
 if not raw:raise ValueError('SCI_MD_011_PUCKWORKS_ROOT_REQUIRED')
 p=Path(raw).resolve()
 if git(p,'rev-parse','HEAD')!=PW_COMMIT or git(p,'rev-parse','HEAD^{tree}')!=PW_TREE or git(p,'status','--short'):raise ValueError('PUCKWORKS_AUTHORITY')
 return p
def production_symbols():
 locations={'poroelasticIntegral':'solver/espressoWholePullFoam/poroelasticCompaction.H','poroelasticUniversalIntegral':'solver/espressoWholePullFoam/poroelasticCompaction.H','poroelasticUniversalQhat':'solver/espressoWholePullFoam/poroelasticCompaction.H','poroelasticPermeabilityRatio':'solver/espressoWholePullFoam/poroelasticCompaction.H','poroelasticPuckFlow':'solver/espressoWholePullFoam/poroelasticCompaction.H','poroelasticSaturatedPuckState':'solver/espressoWholePullFoam/machineBoundaryModel.H'}
 return [{'symbol':s,'path':p,'sha256':hashlib.sha256(symbol_text(ROOT/p,s).encode()).hexdigest()} for s,p in locations.items()]
def generate():
 pw=puckworks();OUT.mkdir(parents=True,exist_ok=True);arts=[{'path':f'docs/analysis/sci_md_010/{n}','sha256':sha256(S10/n)} for n in HANDOFF];sources=[{'path':p,'sha256':sha256(pw/p)} for p in PW_FILES];prod=[{'path':p,'sha256':sha256(ROOT/p)} for p in ('solver/espressoWholePullFoam/poroelasticCompaction.H','solver/espressoWholePullFoam/machineBoundaryModel.H','solver/espressoWholePullFoam/espressoWholePullFoam.C')]
 write_json(OUT/'SCI_MD_010_HANDOFF.json',{'task_id':TASK,'sci_md_010_merge_commit':'375b19b96096cf1d9681ab26efec7ed02b87dd09','sci_md_010_merge_tree':'5ae6135157019048205fe6bcdd6a9c2bce0a51fc','result_head':'72236a656b9d8230e657ce5cb2df4b610f5c1503','freeze_head':'9b1c7ed2505ac5a95768cdd188682e7a6ee6ee77','freeze_tree':'1ef01bd26ee2a45ec509ee8c6afa99eaa009c4a5','freeze_manifest_sha256':'cdac6800b8976290621b1f0e75b484c7b062833d4ebe03fefee51a8789dbf030','result_manifest_sha256':'2e7379806f021bc26649fd8169b07620a85808c74a6f590d4441e07530d3a3d5','artifacts':arts})
 authority={'task_id':TASK,'revision':REVISION,'starting_r0':{'commit':R0,'tree':'31c964eaeb91b8f6190aaab15325e8e1f99afe95','freeze_manifest_file_sha256':'bbff4d488f84fad17509de69a28b057b45a9c2cec6496947c096262c7842e733','review_disposition':'REVIEW_FAIL_MATERIAL_FINDINGS'},'ewp':{'commit':'375b19b96096cf1d9681ab26efec7ed02b87dd09','tree':'5ae6135157019048205fe6bcdd6a9c2bce0a51fc'},'puckworks_analysis':{'commit':PW_COMMIT,'tree':PW_TREE,'worktree':'CLEAN','sources':sources},'production_sources':prod,'production_puckworks_lock':load_json(ROOT/'dependencies/puckworks.lock.json'),'pr_140':'MERGED','issue_139':'CLOSED','stage_f_authorized':False,'stage_d_authorized':False};write_json(OUT/'AUTHORITY_AND_HANDOFF.json',authority)
 observation={'authority':'SCI_MD_010_ACCEPTED_LINE_TO_BASKET_OBSERVATION_ADAPTER','target':{'field':'mass_flow_rate__g_per_s','window':'endpoint_100s','role':'accepted equilibrium proxy; not source 110-120 s full-data calibration'},'predictive_input':{'field':'pressure__bar','time_index':999,'meaning':'directly measured endpoint line pressure; never parsed from condition identity'},'prohibited_inputs':['observed basket pressure','flow-derived basket pressure','target-derived pressure'],'machine_calibration':CAL,'equation':'p_basket_pred=p_line_measured-(a*q_pred^2+b*q_pred+c)','population':{'physical_brews':56,'conditions':11,'outer_folds':11},'membership_authority':'docs/analysis/sci_md_010/FOLD_MEMBERSHIP.csv','source_60_brew_calibration':'CONTEXT_ONLY'};write_json(OUT/'OBSERVATION_INTERFACE.json',observation)
 eq={'task_id':TASK,'production_files':{x['path']:x['sha256'] for x in prod},'production_symbols':production_symbols(),'mapping':{'X':'p_basket/Pc','stressFreePorosity':'fixed Phi','criticalCompactionPressure':'Pc','mobility_geometry_scale':'Qc'},'fixed_phi':PHI,'fixed_phi_authority':'k_solids__g/dose__g = 2.257390325360356/18.5','dense_grid':{'points':100001,'x_min':0,'x_max':1,'max_abs_fphi_minus_f0':max(abs(fphi(i/100000)-f0(i/100000)) for i in range(100001))},'oracle':load_json(OUT/'CLOSURE_ORACLE_RECEIPT.json'),'domain':'0 <= x < 1 prediction; x=1 normalization/oracle only','mass_flow_mapping':'Qc_g_s=1000*rho*A*k0*(1e5*Pc_bar)*J(1,Phi)/(mu*h)','monotone':True,'saturation_capability':True,'turnover_capability':False,'full_production_machine_boundary_equivalence':False,'physical_validation':'NOT_ESTABLISHED'};write_json(OUT/'EWP_CLOSURE_EQUIVALENCE.json',eq)
 specs={'task_id':TASK,'revision':REVISION,'models':[{'model_id':B0,'real_mode':'immutable accepted SCI-MD-010 predictions/scales/parameters/losses'},{'model_id':B1,'equation':'max(0,a0+a1*p_line+a2*p_line^2)','real_mode':'immutable accepted reuse; recomputation integrity only'},{'model_id':P1,'equation':'Qc*x*(4-6*x+4*x^2-x^3)','fitted':['log(Qc_g_s)','log(Pc_bar)']},{'model_id':E2C,'equation':'Qc*J(x,Phi)/J(1,Phi)','fixed_Phi':PHI,'phi_privilege':'TARGET_EXPOSED_SOURCE_CONDITIONED_CONTEXT_NOT_FOLD_FITTED','fitted':['log(Qc_g_s)','log(Pc_bar)']}],'parameterization':'log positive','bounds':BOUNDS,'pc_bound_basis':['positive mathematical parameter domain','exogenous line-pressure design','positive quadratic machine drop means basket pressure is below line pressure','fixed Qc 0-20 g/s safety range','source Pc 12.39 bar and reported approximately 12 +/- 3 bar context','broad deterministic numerical feasibility; invalid combinations receive infinite objective'],'bound_selection_candidate_information_used':False,'optimizer':OPT,'identifiability':IDENT,'physical_parameter_claim':'effective predictive Qc/Pc only; k0,rho,A,h,mu,Y,Phi and wet permeability not identified'};write_json(OUT/'MODEL_SPECIFICATIONS.json',specs)
 contract={'task_id':TASK,'revision':REVISION,'models':list(MODELS),'row_index':'docs/analysis/sci_md_010/ANALYSIS_ROW_INDEX.csv','fold_assignments':'docs/analysis/sci_md_010/FOLD_ASSIGNMENTS.csv','fold_membership':'docs/analysis/sci_md_010/FOLD_MEMBERSHIP.csv','sci_md_010_handoff':'docs/analysis/sci_md_011/SCI_MD_010_HANDOFF.json','observation_interface':'docs/analysis/sci_md_011/OBSERVATION_INTERFACE.json','machine_calibration':CAL,'fixed_phi':PHI,'domain':{'x':'0 <= x < 1','epsilon':DOMAIN_EPS,'pressure_residual_tolerance_bar':PRESSURE_TOL,'coupled_equation_residual_tolerance_bar':COUPLED_RESIDUAL_TOL,'maximum_iterations':MAX_ROOT_ITER,'no_bracket':'structured failed prediction; no clamp/exclusion','nonfinite':'structured rejection','line_pressure_le_c':'zero flow and basket pressure'},'fit':{'objective':'condition-balanced squared flow error g2/s2','bounds':BOUNDS,'optimizer':OPT,'identifiability':IDENT},'metrics':{'primary':'equal-condition mean fold RMSE/training condition-mean-flow range','bootstrap_count':BOOTSTRAPS,'seed':SEED,'bootstrap_refit':False,'unit':'condition_then_paired_brew','quantile':'nearest-rank ceil(p*n)-1','pairs':['B1_VS_P1','B1_VS_E2C','P1_VS_E2C'],'full_and_low_pressure_intervals':True},'gates':{'low_subset_condition_mean_line_pressure_bar':'<=5.25','high_subset_condition_mean_line_pressure_bar':'>=8.5','low':'predicted slope > 0','high':'predicted slope <= 0','finite_vs_universal_gate':'NONE'},'blocked_precedence':True,'current_full_ewp':'NOT_TESTED'};write_json(OUT/'EVALUATION_CONTRACT.json',contract)
 freeze={'task_id':TASK,'revision':REVISION,'supersedes_freeze_commit':R0,'superseded_freeze_disposition':'REVIEW_FAIL_MATERIAL_FINDINGS','governance':'G1','change_declaration':'NO_GOVERNING_PHYSICS_CHANGE','scoring_executed':False,'real_candidate_fits_generated':False,'real_candidate_predictions_generated':False,'real_candidate_scores_generated':False,'phase_b_authorized':False,'stage_f_authorized':False,'stage_d_authorized':False,'current_full_ewp_validated':False,'physical_validation':'NOT_ESTABLISHED','seed':SEED,'bootstrap_count':BOOTSTRAPS,'selected_models':list(MODELS),'production_openfoam_case_count':0,'fixed_phi':PHI,'parameter_bounds':BOUNDS,'optimizer':OPT,'identifiability':IDENT,'puckworks_analysis':authority['puckworks_analysis'],'ewp_base':authority['ewp']};write_json(OUT/'PRE_SCORE_FREEZE.json',freeze)
 (OUT/'EWP_CLOSURE_EQUIVALENCE.md').write_text('# EWP closure equivalence — R1\n\nThe unchanged production closure symbols and file identities are frozen in `EWP_CLOSURE_EQUIVALENCE.json`. Production normalized stress maps to `p_basket/Pc`; `stressFreePorosity` maps to fixed Phi; critical pressure maps to Pc; and mobility/geometry maps to effective Qc. The universal limit, boundary identities, monotonicity, saturation capability, lack of turnover, SI-to-g/s conversion, unique implicit root, and the distinction between the production-equivalent closure and the SCI-MD-010 quadratic observation adapter remain as established in R0.\n\nThe committed 21-row compiled-header oracle receipt independently records every production/Python comparison at 1e-12 absolute and relative tolerance. SCI-MD-011 identifies only effective predictive Qc/Pc and no constituent physical parameter or production input.\n')
 (OUT/'FREEZE_REPORT.md').write_text('# SCI-MD-011 R1 Phase-A freeze report\n\nDisposition: `SCI_MD_011_R1_PRE_SCORE_FREEZE_READY_FOR_SINGLE_INDEPENDENT_REVIEW`.\n\nR1 supersedes the failed R0 freeze without removing it from history. It enables the already-reviewed real execution path subject to an exact PASS receipt, binds authoritative membership and immutable B0/B1 reuse, makes blocked science writable, corrects Pc to a broad 1–100 bar range that includes 12.39 and 9–15 bar, strengthens deterministic fitting and effective-parameter diagnostics, persists the compiled 21-row oracle, completes diagnostics, and independently recomputes result packages. No real candidate was fitted, predicted, or scored.\n')
 manifest={'task_id':TASK,'revision':REVISION,'scoring_executed':False,'artifacts':[{'path':p,'sha256':sha256(ROOT/p)} for p in FREEZE_FILES]};manifest['aggregate_content_sha256']=hashlib.sha256(''.join(a['sha256'] for a in manifest['artifacts']).encode()).hexdigest();write_json(OUT/'FREEZE_ARTIFACT_MANIFEST.json',manifest)
def validate():
 puckworks();h=load_json(OUT/'SCI_MD_010_HANDOFF.json')
 for a in h['artifacts']:
  if sha256(ROOT/a['path'])!=a['sha256']:raise ValueError('HANDOFF_CHANGED:'+a['path'])
 f=load_json(OUT/'PRE_SCORE_FREEZE.json');o=load_json(OUT/'CLOSURE_ORACLE_RECEIPT.json')
 if f['revision']!='R1' or f['parameter_bounds']!=BOUNDS or not o['pass'] or o['row_count']!=21:raise ValueError('R1_FREEZE_INVALID')
 return {'joined_rows':56,'distinct_physical_brews':56,'pressure_conditions':11,'outer_folds':11,'alias_duplication':0,'candidate_real_fits':0,'candidate_real_predictions':0,'candidate_real_scores':0}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--validate-only',action='store_true');a=ap.parse_args()
 if not a.validate_only:generate()
 print(json.dumps(validate(),sort_keys=True))
if __name__=='__main__':main()
