"""Frozen artifact builder for XSV-PANNUSCH-EWP-INPUT-MAPPING-001."""
from __future__ import annotations
import csv, hashlib, json
from collections import Counter
from decimal import Decimal, getcontext
from pathlib import Path

TASK="XSV-PANNUSCH-EWP-INPUT-MAPPING-001"
DISP="XSV_PANNUSCH_EWP_INPUT_MAPPING_001_CONTEXT_ONLY_PRESERVE_INDEPENDENT_INPUT_TREATMENTS"
CLAIM="SOURCE_AUTHORITY_AND_INTERFACE_SEMANTICS_QUALIFICATION_ONLY"
OUT=Path(__file__).resolve().parents[2]/"docs/analysis/xsv_pannusch_ewp_input_mapping_001"
REG_FIELDS="system input_id symbol_or_key primary_role physical_quantity source_or_consumer_path source_symbol_or_locator authority_class value_status value_or_domain units basis spatial_support measurement_location temporal_support clock initial_state runtime_consumer_status validity_range evidence_reference notes".split()
MAP_FIELDS="mapping_id pannusch_input_id ewp_input_id mapping_role proposed_adapter_expression source_authority_gate physical_quantity_gate unit_basis_gate spatial_support_gate measurement_location_gate temporal_support_gate clock_gate state_gate existing_consumer_gate no_constitutive_inference_gate no_calibration_gate no_governing_physics_change_gate deterministic_adapter_gate claim_boundary_gate mapping_classification operationally_qualified context_compatible rejection_reason evidence_references".split()

def r(system,i,key,role,quantity,path,locator,authority,status,value,units,basis,support,location,temporal,clock,state,consumer,validity,evidence,notes=""):
 return dict(zip(REG_FIELDS,[system,i,key,role,quantity,path,locator,authority,status,value,units,basis,support,location,temporal,clock,state,consumer,validity,evidence,notes]))

def registry():
 p="puckworks/models/pannusch2024/solver.py"; c="puckworks/models/pannusch2024/closures.py"; pc="puckworks/data/pannusch2024/prediction_conditions.csv"
 rows=[
 r("PANNUSCH","P-Q-CONST","flow_start_mL_s=flow_end_mL_s","SOURCE_PROGRAMMED_INPUT","programmed flow command",pc,"PRED-C01/C02/C03/C04/C05/C06","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","1.7;2.0;2.3","mL/s (table label)","whole-machine command","programme","machine command; not measured puck face","shot-constant command","SOURCE_PROGRAM_TIME","preinfused/saturated","NOT_APPLICABLE","1-3 mL/s model domain","PW-PRED-CONDITIONS","Python mass/density convention remains unresolved"),
 r("PANNUSCH","P-Q0","flow_start_mL_s","SOURCE_PROGRAMMED_INPUT","programmed start flow",pc,"PRED-C07/C08 start","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","1.7;2.3","mL/s (table label)","whole-machine command","programme start","machine command","start scalar only","programme zero unresolved","preinfused/saturated","NOT_APPLICABLE","gradient endpoints only","PREDECESSOR-FLOW","Retained scalar-start treatment; not a full history"),
 r("PANNUSCH","P-QT","Q(t)","SOURCE_AUTHORITY_UNRESOLVED","flow history",pc,"C07/C08 endpoints","SOURCE_EXPERIMENT_DESIGN","NOT_AVAILABLE","UNRESOLVED","UNRESOLVED","UNRESOLVED","programme","machine command","history unavailable","programme/solver clock unresolved","preinfused/saturated","NOT_APPLICABLE","none established","PREDECESSOR-FLOW","No interpolation/holds/duration authority"),
 r("PANNUSCH","P-Q-GRAD-END","flow_start_mL_s;flow_end_mL_s","SOURCE_PROGRAMMED_INPUT","programmed flow endpoints",pc,"PRED-C07/C08","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","1.7->2.3;2.3->1.7","mL/s (table label)","endpoint commands","programme","machine command","two endpoints","programme coordinate unresolved","preinfused/saturated","NOT_APPLICABLE","C07/C08","PREDECESSOR-FLOW","Not an exact schedule"),
 r("PANNUSCH","P-MASSDATA-FLOW","MassData.flow","SOURCE_RECONSTRUCTED_DIAGNOSTIC","beverage mass derivative","external P24-MASS-PRED","MassData.flow","SOURCE_DERIVED_TELEMETRY","AVAILABLE_EXTERNAL","vector","g/s","outlet beverage mass","basket outlet/scale","beverage scale","time series","scale clock","unknown","NOT_APPLICABLE","prediction shots","PREDECESSOR-FLOW","Not inlet volumetric flow"),
 r("PANNUSCH","P-Q-DIV098","MassData.flow/0.98","SOURCE_RECONSTRUCTED_DIAGNOSTIC","density-adjusted beverage derivative","external released MATLAB","plotted /0.98","SOURCE_CODE","AVAILABLE_EXTERNAL","vector","mL/s purported","outlet beverage; undocumented density","basket outlet/scale","scale","time series","scale clock","unknown","NOT_APPLICABLE","prediction shots","PREDECESSOR-FLOW","Unauthorized plotted diagnostic"),
 r("PANNUSCH","P-BEV-DM-DT","d(beverage mass)/dt","SOURCE_RECONSTRUCTED_DIAGNOSTIC","beverage mass derivative","external P24-MASS-PRED","quadratic mass fit derivative","SOURCE_DERIVED_TELEMETRY","AVAILABLE_EXTERNAL","vector","g/s","outlet beverage mass","basket outlet","scale","time series","scale clock","unknown","NOT_APPLICABLE","prediction shots","PREDECESSOR-FLOW","Outlet not inlet"),
 r("PANNUSCH","P-DURATION","shot/fraction duration","SOURCE_OBSERVER_OR_RUN_CONTROL","observation duration","puckworks/data/pannusch2024/prediction_fraction_replicates.csv","fraction times","SOURCE_DERIVED_TELEMETRY","AVAILABLE","per shot","s","observer window","fraction collection","scale/fraction observer","interval","scale/fraction clock","unknown","NOT_APPLICABLE","source shots","PW-DATA-DICTIONARY"),
 r("PANNUSCH","P-TBOUNDS","t_bounds","SOURCE_OBSERVER_OR_RUN_CONTROL","fraction bounds",p,"simulate_fractions:t_bounds","SOURCE_DERIVED_TELEMETRY","AVAILABLE","six intervals","s","observer bounds","fraction collection","scale/fraction observer","interval endpoints","scale/fraction clock","saturated","NOT_APPLICABLE","source shots","PW-SOLVER"),
 r("PANNUSCH","P-CLOCKS","programme/solver/scale/first-drip clocks","SOURCE_AUTHORITY_UNRESOLVED","clock relationships","docs/analysis/sci_md_pannusch_flow_history_001/FLOW_CLOCK_QUALIFICATION.json","clock audit","MERGED_PREDECESSOR","UNRESOLVED","UNRESOLVED","s","multiple clocks","multiple","multiple","multiple","UNRESOLVED","multiple","NOT_APPLICABLE","none established","PREDECESSOR-CLOCK"),
 r("PANNUSCH","P-T-CONST","temperature_start_C=temperature_end_C","SOURCE_PROGRAMMED_INPUT","programmed water temperature",pc,"PRED-C01/C02/C05/C06/C07/C08","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","86;90;92","degC","machine command","programme","machine command; not measured bed","shot-constant command","source programme time","isothermal model","NOT_APPLICABLE","80-98 degC","PW-PRED-CONDITIONS"),
 r("PANNUSCH","P-T-END","temperature endpoints","SOURCE_PROGRAMMED_INPUT","programmed temperature endpoints",pc,"PRED-C03/C04","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","88->93;93->88","degC","endpoint commands","programme","machine command","two endpoints","source programme time","isothermal model assumption conflicts with ramp","NOT_APPLICABLE","80-98 degC","PW-PRED-CONDITIONS"),
 r("PANNUSCH","P-TT","T(t)","SOURCE_AUTHORITY_UNRESOLVED","temperature history",pc,"temperature_schedule","SOURCE_EXPERIMENT_DESIGN","NOT_AVAILABLE","UNRESOLVED","degC","UNRESOLVED","programme","machine command","history unavailable","clock unresolved","UNRESOLVED","NOT_APPLICABLE","none established","PW-PRED-CONDITIONS"),
 r("PANNUSCH","P-TREF","TREF_K","SOURCE_FIXED_MODEL_CONSTANT","van't Hoff reference temperature",c,"TREF_K","SOURCE_CODE","AVAILABLE","360.15","K","closure reference","model-global","not measured","constant","model time","isothermal","NOT_APPLICABLE","closure only","PW-CLOSURES"),
 r("PANNUSCH","P-RHO","water_density(T); RHO","SOURCE_DERIVED_CLOSURE","water density",c,"water_density; solver.RHO","SOURCE_CODE","AVAILABLE","correlation;980","kg/m3","pure-water/model constant","model-global","not measured","temperature-dependent/fixed","model time","isothermal","NOT_APPLICABLE","80-98 degC","PW-CLOSURES","Conflicting roles; not conversion authority"),
 r("PANNUSCH","P-ETA","water_viscosity(T)","SOURCE_DERIVED_CLOSURE","dynamic viscosity",c,"water_viscosity","SOURCE_CODE","AVAILABLE","correlation","Pa s","pure water","model-global","not measured","temperature-dependent","model time","isothermal","NOT_APPLICABLE","80-98 degC","PW-CLOSURES"),
 r("PANNUSCH","P-DI","diffusion_coeff(T,solute)","SOURCE_DERIVED_CLOSURE","molecular diffusivity",c,"diffusion_coeff","SOURCE_CODE","AVAILABLE","Wilke-Chang","m2/s","free molecular/pure water","solute-specific","not measured","temperature-dependent","model time","isothermal","NOT_APPLICABLE","80-98 degC","PW-CLOSURES"),
 r("PANNUSCH","P-MOLPROP","SOLUTES M/MV","SOURCE_FIXED_MODEL_CONSTANT","molecular properties",c,"SOLUTES","SOURCE_CODE","AVAILABLE","four pseudo/solutes","g/mol;cm3/mol","solute molecule","solute-specific","not measured","constant","model time","isothermal","NOT_APPLICABLE","model solutes","PW-CLOSURES"),
 r("PANNUSCH","P-DBED","DBED","SOURCE_FIXED_MODEL_CONSTANT","basket diameter",p,"DBED","SOURCE_CODE","AVAILABLE","0.058","m","nominal circular bed","whole basket","model geometry","constant","model time","saturated","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-ACS","ACS","SOURCE_DERIVED_CLOSURE","basket cross-sectional area",p,"DBED**2*pi/4","SOURCE_CODE","AVAILABLE","derived","m2","nominal circular bed","whole basket","model geometry","constant","model time","saturated","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-L","L","SOURCE_FIXED_MODEL_CONSTANT","bed depth",p,"L","SOURCE_CODE","AVAILABLE","0.015","m","fixed model bed","whole basket","model geometry","constant","model time","saturated","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-DOSE","M_0","SOURCE_SCENARIO_ASSUMPTION","dose basis","docs/cards/pannusch2024.md","default M_0","SOURCE_DOCUMENTATION","AVAILABLE","20","g dry coffee","whole basket dry dose","whole basket","scenario","constant","model time","saturated","NOT_APPLICABLE","source model","PW-CARD"),
 r("PANNUSCH","P-ALPHA-L","ALPHA_L","SOURCE_FIXED_MODEL_CONSTANT","bulk liquid porosity",p,"ALPHA_L","SOURCE_CODE","AVAILABLE","0.17","1","bulk liquid volume/bed volume","whole bed","model state","constant","model time","saturated","NOT_APPLICABLE","source model","PW-SOLVER","Card says measured per-grind values not provided; implementation constant"),
 r("PANNUSCH","P-PHI-V2","PHI_V2","SOURCE_FIXED_MODEL_CONSTANT","coarse intragranular porosity",p,"PHI_V2","SOURCE_CODE","AVAILABLE","0.4","1","coarse-particle internal pore fraction","coarse particles","model state","constant","model time","saturated","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-SATURATED","fully saturated/preinfused t=0","SOURCE_INITIAL_CONDITION","initial wetting state",p,"c0 and card IC","SOURCE_MODEL_CONTRACT","AVAILABLE","fully saturated","state","bulk bed","whole bed","model state","t=0 after preinfusion","solver zero","saturated","NOT_APPLICABLE","source model","PW-CARD"),
 r("PANNUSCH","P-CLEAN-INLET","c_l(t,0)=0","SOURCE_INITIAL_CONDITION","inlet solute concentration",p,"_rhs cl[0]=0","SOURCE_MODEL_CONTRACT","AVAILABLE","0","normalized concentration","clean solvent","bed inlet","model boundary","all t","solver clock","saturated","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-1D","homogeneous unidirectional 1D","SOURCE_SCENARIO_ASSUMPTION","flow geometry assumption","docs/cards/pannusch2024.md","assumptions","SOURCE_DOCUMENTATION","AVAILABLE","homogeneous 1D","state","whole bed","whole bed","model domain","all t","model time","saturated","NOT_APPLICABLE","source model","PW-CARD"),
 r("PANNUSCH","P-DS1","D1_FINE","SOURCE_MEASURED_INPUT","fine PSD peak",p,"D1_FINE","SOURCE_INSTRUMENT_SUMMARY","AVAILABLE","24e-6","m","dry PSD representative peak","particles","dry PSD","constant","source campaign","dry","NOT_APPLICABLE","grinds 1.4-2.0","PW-SOLVER"),
 r("PANNUSCH","P-DS2","GRINDS.d_s2","SOURCE_FITTED_PARAMETER","coarse representative size",p,"GRINDS d_s2","SOURCE_FITTED_TABLE","AVAILABLE","301-332e-6","m","fitted two-grain class","particles","model parameter","per grind","fit campaign","model","NOT_APPLICABLE","grinds 1.4-2.0","PW-GRIND-TABLE"),
 r("PANNUSCH","P-D32","D32/recomputed d32","SOURCE_MEASURED_INPUT","Sauter diameter",c,"D32; solver recomputation","SOURCE_INSTRUMENT_SUMMARY","AVAILABLE","84e-6/card; recomputed","m","dry PSD/Sauter","particles","dry PSD/model","constant/per grind","fit campaign","dry","NOT_APPLICABLE","source model","PW-CLOSURES","Implementation paths differ"),
 r("PANNUSCH","P-PSI","GRINDS.psi","SOURCE_FITTED_PARAMETER","fines volume fraction",p,"GRINDS psi","SOURCE_FITTED_TABLE","AVAILABLE","0.19;0.23;0.22","1","fitted particle volume fraction","whole bed","model parameter","per grind","fit campaign","model","NOT_APPLICABLE","grinds 1.4-2.0","PW-GRIND-TABLE"),
 r("PANNUSCH","P-GRIND","grind","SOURCE_PROGRAMMED_INPUT","grinder setting label","puckworks/data/pannusch2024/experiment_grind_assignments.csv","grind assignment","SOURCE_EXPERIMENT_DESIGN","AVAILABLE","1.4;1.7;2.0","ordinal dial","apparatus-specific label","coffee preparation","source apparatus","per shot","campaign","dry","NOT_APPLICABLE","EK43 source apparatus","PW-GRIND-ASSIGN"),
 r("PANNUSCH","P-SOLUTE","solute","SOURCE_SCENARIO_ASSUMPTION","solute identity","puckworks/data/pannusch2024/table2_fitted_params.csv","solute","SOURCE_FITTED_TABLE","AVAILABLE","caffeine;trigonelline;5CQA;tds","identity","named analyte/pseudo","component","analytical/model","constant","campaign","saturated","NOT_APPLICABLE","four components","PW-FITTED-TABLE"),
 r("PANNUSCH","P-AB","A1/B1/A2/B2","SOURCE_FITTED_PARAMETER","Sherwood fit coefficients","puckworks/data/pannusch2024/table2_fitted_params.csv","A1 B1 A2 B2","SOURCE_FITTED_TABLE","AVAILABLE","component-specific","1","Pannusch Sherwood closure","particle classes","model parameter","constant","fit campaign","saturated","NOT_APPLICABLE","fitted range","PW-FITTED-TABLE"),
 r("PANNUSCH","P-KREF","K_ref","SOURCE_FITTED_PARAMETER","distribution coefficient reference",c,"vant_hoff_K Kref","SOURCE_FITTED_TABLE","AVAILABLE","component-specific","1","solid-liquid equilibrium","component/model","model parameter","constant","fit campaign","saturated","NOT_APPLICABLE","fitted range","PW-FITTED-TABLE"),
 r("PANNUSCH","P-GAMMA","gamma","SOURCE_FITTED_PARAMETER","van't Hoff slope",c,"vant_hoff_K gamma","SOURCE_FITTED_TABLE","AVAILABLE","component-specific","K","Pannusch equilibrium closure","component/model","model parameter","constant","fit campaign","saturated","NOT_APPLICABLE","fitted range","PW-FITTED-TABLE"),
 r("PANNUSCH","P-CS0","c_s0","SOURCE_FITTED_PARAMETER","initial solid concentration",p,"sp[c_s0]","SOURCE_FITTED_TABLE","AVAILABLE","4.19-182","mg/mL","Pannusch solid concentration","particle phases","model parameter","t=0","fit campaign","saturated equilibrium","NOT_APPLICABLE","fitted range","PW-FITTED-TABLE","Not production inventory"),
 r("PANNUSCH","P-CL1","cl1","SOURCE_SCENARIO_ASSUMPTION","normalization concentration",p,"simulate_fractions cl1","SOURCE_MODEL_INTERFACE","AVAILABLE","component/scenario","concentration","normalization basis","liquid phase","model normalization","constant","solver clock","equilibrium initial liquid","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-EQ-IC","cl=K*c_s0","SOURCE_INITIAL_CONDITION","equilibrium initial liquid",p,"c0 initialization","SOURCE_MODEL_CONTRACT","AVAILABLE","K*c_s0","concentration","Pannusch phase equilibrium","whole bed liquid","model state","t=0","solver zero","saturated equilibrium","NOT_APPLICABLE","source model","PW-SOLVER"),
 r("PANNUSCH","P-TDS-PSEUDO","TDS uses caffeine molecule","SOURCE_SCENARIO_ASSUMPTION","pseudo-solute molecular identity",c,"SOLUTES[tds]","SOURCE_CODE","AVAILABLE","caffeine-like","identity","pseudo molecule","component","model assumption","constant","model time","saturated","NOT_APPLICABLE","TDS only","PW-CLOSURES"),
 ]
 e="scripts/prepare_case.py"
 rows += [
 r("EWP","E-FLOW-MODE","boundary_mode=prescribed_flow","EXISTING_RUNTIME_BOUNDARY_INPUT","hydraulic boundary mode",e,"boundary_mode","RUNTIME_CONSUMER","AVAILABLE","prescribed_flow","enum","case mode","whole basket inlet","boundary","run","solver clock","requires saturated/static eligible state","CONSUMED","qualified interface","EWP-PREPARE"),
 r("EWP","E-FLOW-TYPE","prescribedFlowBoundary.scheduleType","EXISTING_RUNTIME_BOUNDARY_INPUT","flow schedule type",e,"scheduleType","RUNTIME_CONSUMER","AVAILABLE","constant|piecewiseLinear","enum","full-basket flow schedule","whole basket inlet","boundary","run","solver clock","eligible modes only","CONSUMED","XSV-FLOW-001","EWP-PREPARE"),
 r("EWP","E-FLOW-CONST","volumetricFlowRateM3PerS","EXISTING_RUNTIME_BOUNDARY_INPUT","volumetric flow rate",e,"volumetricFlowRateM3PerS","RUNTIME_CONSUMER","AVAILABLE","finite >=0","m3/s","full-basket liquid volumetric flow","whole basket","puck inlet boundary","shot constant","solver clock","initially saturated/static Darcy restrictions","CONSUMED","XSV-FLOW-001","EWP-PREPARE"),
 r("EWP","E-FLOW-TIMES","timesS","EXISTING_RUNTIME_BOUNDARY_INPUT","schedule times",e,"timesS","RUNTIME_CONSUMER","AVAILABLE","strict increasing covering run","s","solver schedule","whole basket inlet","boundary","piecewise endpoints","solver clock","eligible modes only","CONSUMED","XSV-FLOW-001","EWP-PREPARE"),
 r("EWP","E-FLOW-VALUES","volumetricFlowRatesM3PerS","EXISTING_RUNTIME_BOUNDARY_INPUT","volumetric flow schedule",e,"volumetricFlowRatesM3PerS","RUNTIME_CONSUMER","AVAILABLE","finite >=0","m3/s","full-basket liquid volumetric flow","whole basket","puck inlet boundary","piecewise linear","solver clock","eligible modes only","CONSUMED","XSV-FLOW-001","EWP-PREPARE"),
 r("EWP","E-FLOW-TOL","absoluteFlowToleranceM3PerS/relativeFlowTolerance","EXISTING_NUMERICAL_CONTROL","flow numerical tolerance",e,"tolerance keys","RUNTIME_CONSUMER","AVAILABLE","positive","m3/s;1","numerical","solver","numerical acceptance","run","solver clock","any prescribed-flow eligible","CONSUMED","XSV-FLOW-001","Never mappable"),
 r("EWP","E-RADIUS","geometry.basket_radius_m","EXISTING_RUNTIME_GEOMETRY_INPUT","basket radius",e,"basket_radius_m","RUNTIME_CONSUMER","AVAILABLE","positive","m","nominal circular basket","whole basket","mesh geometry","constant","case","case state","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-DOSE","coffee_bed.dry_dose_kg","EXISTING_RUNTIME_PROPERTY_INPUT","dry dose",e,"dry_dose_kg","RUNTIME_CONSUMER","AVAILABLE","positive","kg","whole-basket dry coffee","whole basket","case property","constant","case","case state","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-POROSITY","coffee_bed.initial_porosity","EXISTING_RUNTIME_PROPERTY_INPUT","bulk initial porosity",e,"initial_porosity","RUNTIME_CONSUMER","AVAILABLE","0..1","1","bulk bed void fraction","whole bed","initial field/property","t=0","solver zero","case-selected","CONSUMED","0<phi<1","EWP-PREPARE"),
 r("EWP","E-SATURATION","wetting model/initial saturation selector","EXISTING_INITIAL_CONDITION_SELECTOR","initial saturation state",e,"wetting and prescribed-flow eligibility","RUNTIME_CONSUMER","AVAILABLE","initially saturated eligible mode","state","bulk bed","whole bed","initial field","t=0","solver zero","saturated selector","CONSUMED","XSV-FLOW-001","EWP-PREPARE"),
 r("EWP","E-INLET-ZERO","inlet dissolvedConcentration=0","EXISTING_RUNTIME_BOUNDARY_INPUT","inlet solute concentration","scripts/prepare_case.py","0 field inlet","RUNTIME_CONSUMER","AVAILABLE","0","kg/m3","effective solute liquid","puck inlet","boundary","run","solver clock","case state","CONSUMED","current cases","EWP-PREPARE"),
 r("EWP","E-MU","liquid.dynamic_viscosity_Pa_s","EXISTING_RUNTIME_PROPERTY_INPUT","dynamic viscosity",e,"dynamic_viscosity_Pa_s","RUNTIME_CONSUMER","AVAILABLE","positive","Pa s","effective case liquid","whole domain","property","constant","case","case state","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-DEFF","liquid.effective_solute_diffusivity_m2_s","EXISTING_CONSTITUTIVE_PARAMETER","effective porous diffusivity",e,"effective_solute_diffusivity_m2_s","RUNTIME_CONSUMER","AVAILABLE","nonnegative","m2/s","effective porous transport","whole domain/species","constitutive","constant","case","case state","CONSUMED","nonnegative","EWP-PREPARE"),
 r("EWP","E-PERMEABILITY","coffee_bed.saturated_permeability_m2","EXISTING_CONSTITUTIVE_PARAMETER","effective permeability",e,"saturated_permeability_m2","RUNTIME_CONSUMER","AVAILABLE","positive","m2","effective bed hydraulics","whole bed","constitutive","case","solver clock","mode-dependent","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-INVENTORY","initialExtractable/remainingExtractable","EXISTING_CONSTITUTIVE_PARAMETER","extractable inventory",e,"initial_extractable_fraction_dry_basis","RUNTIME_CONSUMER","AVAILABLE","case/species","kg/kg dry","dry coffee inventory","whole bed/species","initial field","t=0","solver zero","case state","CONSUMED","model restrictions","EWP-PREPARE"),
 r("EWP","E-CAPACITY","saturation_concentration_kg_m3","EXISTING_CONSTITUTIVE_PARAMETER","liquid concentration capacity",e,"saturation_concentration_kg_m3","RUNTIME_CONSUMER","AVAILABLE","positive","kg/m3","effective-solute liquid capacity","liquid phase","constitutive","constant","solver clock","case state","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-KEXT","rate_constant_1_s","EXISTING_CONSTITUTIVE_PARAMETER","extraction rate constant",e,"rate_constant_1_s","RUNTIME_CONSUMER","AVAILABLE","nonnegative","1/s","EWP source law","whole bed/species","constitutive","constant","solver clock","case state","CONSUMED","nonnegative","EWP-PREPARE"),
 r("EWP","E-END","time.end_s","EXISTING_OBSERVER_OR_RUN_CONTROL","run end time",e,"end_s -> controlDict endTime","RUNTIME_CONSUMER","AVAILABLE","positive","s","solver run control","case","run control","endpoint","solver clock","case state","CONSUMED","positive","EWP-PREPARE"),
 r("EWP","E-FRACTIONS","fractionCollection","EXISTING_OBSERVER_OR_RUN_CONTROL","fraction observer bounds",e,"fraction_collection_contract","RUNTIME_CONSUMER","AVAILABLE","optional","kg beverage bounds","observer","outlet","observer","run","solver/cumulative mass","case state","CONSUMED","optional","EWP-PREPARE"),
 r("EWP","E-TEMP","temperature","DOCUMENTED_CONTEXT_WITH_NO_RUNTIME_CONSUMER","temperature state", "docs/MODEL_SPECIFICATION.md","reference temperature","DOCUMENTATION_ONLY","NOT_AVAILABLE","reference only","K","metadata","none","none","none","none","none","NO_EXISTING_CONSUMER","none","EWP-MODEL-SPEC","No runtime temperature field/key"),
 r("EWP","E-PARTICLE","particle classes/grind label","NO_EXISTING_CONSUMER","particle representation", "docs/MODEL_SPECIFICATION.md","none","NONE","NOT_AVAILABLE","none","none","none","none","none","none","none","none","NO_EXISTING_CONSUMER","none","EWP-CONSUMER-AUDIT"),
 ]
 return rows

def m(mid,p,e,role,classification,reason,context=False,gates=None,expr="NONE"):
 g={k:"PASS" for k in ["source_authority_gate","physical_quantity_gate","unit_basis_gate","spatial_support_gate","measurement_location_gate","temporal_support_gate","clock_gate","state_gate","existing_consumer_gate","no_constitutive_inference_gate","no_calibration_gate","no_governing_physics_change_gate","deterministic_adapter_gate","claim_boundary_gate"]}
 if gates:g.update(gates)
 operational=role.startswith("OPERATIONAL_") and all(v=="PASS" for v in g.values())
 return dict(mapping_id=mid,pannusch_input_id=p,ewp_input_id=e,mapping_role=role,proposed_adapter_expression=expr,**g,mapping_classification=classification,operationally_qualified=str(operational).lower(),context_compatible=str(context).lower(),rejection_reason=reason,evidence_references=f"{p};{e};UNIT_BASIS_AUDIT")

def mappings():
 F="FAIL"; U="UNRESOLVED"
 return [
 m("M-FLOW-CONST","P-Q-CONST","E-FLOW-CONST","OPERATIONAL_BOUNDARY_INPUT","UNIT_OR_BASIS_UNRESOLVED","Python identifier/table says mL/s but solver applies mass/density convention",gates={"unit_basis_gate":U,"measurement_location_gate":U,"deterministic_adapter_gate":U},expr="UNRESOLVED: H_VOL versus H_MASS"),
 m("M-FLOW-Q0","P-Q0","E-FLOW-CONST","OPERATIONAL_BOUNDARY_INPUT","TEMPORAL_SUPPORT_MISMATCH","start scalar cannot represent a full gradient shot",gates={"temporal_support_gate":F,"clock_gate":U,"unit_basis_gate":U}),
 m("M-FLOW-HISTORY","P-QT","E-FLOW-VALUES","OPERATIONAL_BOUNDARY_INPUT","SOURCE_AUTHORITY_INELIGIBLE","no authorized history or clock",gates={"source_authority_gate":F,"unit_basis_gate":U,"temporal_support_gate":F,"clock_gate":F,"deterministic_adapter_gate":F}),
 m("M-FLOW-ENDPOINTS","P-Q-GRAD-END","E-FLOW-VALUES","OPERATIONAL_BOUNDARY_INPUT","REQUIRES_SPATIAL_OR_TEMPORAL_RECONSTRUCTION","C07/C08 endpoints cannot create a schedule",gates={"temporal_support_gate":F,"clock_gate":F,"deterministic_adapter_gate":F}),
 m("M-MASSDATA","P-MASSDATA-FLOW","E-FLOW-CONST","OPERATIONAL_BOUNDARY_INPUT","OUTLET_FLOW_NOT_INLET_FLOW","beverage mass derivative is outlet g/s",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"spatial_support_gate":F,"measurement_location_gate":F,"clock_gate":U}),
 m("M-DIV098","P-Q-DIV098","E-FLOW-CONST","OPERATIONAL_BOUNDARY_INPUT","SOURCE_AUTHORITY_INELIGIBLE","plotted /0.98 diagnostic lacks authorized density/basis",gates={"source_authority_gate":F,"physical_quantity_gate":F,"unit_basis_gate":F,"measurement_location_gate":F}),
 m("M-BEV-DERIV","P-BEV-DM-DT","E-FLOW-CONST","OPERATIONAL_BOUNDARY_INPUT","OUTLET_FLOW_NOT_INLET_FLOW","outlet beverage derivative is not inlet volumetric flow",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"measurement_location_gate":F}),
 m("M-T-CONST","P-T-CONST","E-TEMP","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","EWP has no runtime temperature consumer",gates={"existing_consumer_gate":F,"measurement_location_gate":U},context=True),
 m("M-T-END","P-T-END","E-TEMP","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","endpoints are not T(t) and EWP has no consumer",gates={"temporal_support_gate":F,"clock_gate":U,"existing_consumer_gate":F},context=True),
 m("M-TREF","P-TREF","E-TEMP","DOCUMENTATION_ONLY_COMPATIBILITY","SEMANTIC_QUANTITY_MISMATCH","closure reference is not case temperature",gates={"physical_quantity_gate":F,"existing_consumer_gate":F}),
 m("M-DBED","P-DBED","E-RADIUS","GEOMETRY_CONTEXT_COMPATIBILITY","CONTEXT_ONLY_NOT_OPERATIONAL","same nominal 58 mm geometry but source is fixed model constant, not transferable measured case geometry",context=True,expr="radius_m = DBED/2"),
 m("M-ACS","P-ACS","E-RADIUS","GEOMETRY_CONTEXT_COMPATIBILITY","CONTEXT_ONLY_NOT_OPERATIONAL","derived nominal area is context only",context=True,expr="radius_m = sqrt(ACS/pi)"),
 m("M-L","P-L","NO_EWP_RUNTIME_CONSUMER","GEOMETRY_CONTEXT_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","EWP height is dose/density/porosity-derived",gates={"existing_consumer_gate":F},context=True),
 m("M-DOSE","P-DOSE","E-DOSE","SCENARIO_ASSUMPTION_COMPATIBILITY","CONTEXT_ONLY_NOT_OPERATIONAL","20 g scenario coincidence is not measured transferable input",context=True,expr="dose_kg = 20/1000"),
 m("M-ALPHA","P-ALPHA-L","E-POROSITY","OPERATIONAL_PROPERTY_INPUT","SOURCE_AUTHORITY_INELIGIBLE","implementation constant cannot be promoted over unavailable per-grind measured porosity",gates={"source_authority_gate":F,"state_gate":U}),
 m("M-PHIV2","P-PHI-V2","E-POROSITY","OPERATIONAL_PROPERTY_INPUT","SEMANTIC_QUANTITY_MISMATCH","coarse intragranular porosity is not bulk porosity",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"spatial_support_gate":F}),
 m("M-SATURATED","P-SATURATED","E-SATURATION","INITIAL_CONDITION_COMPATIBILITY","CONTEXT_ONLY_NOT_OPERATIONAL","compatible initially saturated mode; changes no default and supplies no operational primitive",context=True),
 m("M-CLEAN","P-CLEAN-INLET","E-INLET-ZERO","INITIAL_CONDITION_COMPATIBILITY","CONTEXT_ONLY_NOT_OPERATIONAL","clean inlet state compatibility only",context=True),
 m("M-1D","P-1D","NO_EWP_RUNTIME_CONSUMER","SCENARIO_ASSUMPTION_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","model assumption is not an EWP input",gates={"existing_consumer_gate":F},context=True),
 m("M-DS1","P-DS1","E-PARTICLE","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","no EWP particle-diameter consumer",gates={"existing_consumer_gate":F},context=True),
 m("M-DS2","P-DS2","E-PARTICLE","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","fitted coarse size and no consumer",gates={"existing_consumer_gate":F,"no_calibration_gate":F}),
 m("M-D32","P-D32","E-PARTICLE","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","no direct consumer and implementation identity differs",gates={"existing_consumer_gate":F,"source_authority_gate":U},context=True),
 m("M-PSI","P-PSI","E-PARTICLE","DOCUMENTATION_ONLY_COMPATIBILITY","NO_EWP_RUNTIME_CONSUMER","fitted fines fraction and no consumer",gates={"existing_consumer_gate":F,"no_calibration_gate":F}),
 m("M-GRIND","P-GRIND","E-PERMEABILITY","OPERATIONAL_PROPERTY_INPUT","REQUIRES_CONSTITUTIVE_INFERENCE","dial label cannot determine permeability",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_constitutive_inference_gate":F}),
 m("M-ETA","P-ETA","E-MU","OPERATIONAL_PROPERTY_INPUT","REQUIRES_CONSTITUTIVE_INFERENCE","Pannusch pure-water closure cannot replace independently specified EWP effective liquid property",gates={"source_authority_gate":F,"state_gate":U,"no_constitutive_inference_gate":F}),
 m("M-DI","P-DI","E-DEFF","OPERATIONAL_PROPERTY_INPUT","SEMANTIC_QUANTITY_MISMATCH","molecular free-liquid D is not EWP effective porous D",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_constitutive_inference_gate":F}),
 m("M-CS0","P-CS0","E-INVENTORY","OPERATIONAL_PROPERTY_INPUT","REQUIRES_CALIBRATION_OR_REFIT","fitted concentration is not dry-basis extractable inventory",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_calibration_gate":F,"state_gate":F}),
 m("M-KREF","P-KREF","E-CAPACITY","OPERATIONAL_PROPERTY_INPUT","SEMANTIC_QUANTITY_MISMATCH","distribution coefficient is not concentration capacity",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_calibration_gate":F}),
 m("M-AB-KEXT","P-AB","E-KEXT","OPERATIONAL_PROPERTY_INPUT","REQUIRES_CONSTITUTIVE_INFERENCE","Sherwood fit coefficients are not EWP k_ext",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_constitutive_inference_gate":F,"no_calibration_gate":F}),
 m("M-DURATION","P-DURATION","E-END","OBSERVER_OR_RUN_CONTROL_COMPATIBILITY","CLOCK_MAPPING_UNRESOLVED","common duration does not establish same clock",gates={"clock_gate":U},context=True),
 m("M-TBOUNDS","P-TBOUNDS","E-FRACTIONS","OBSERVER_OR_RUN_CONTROL_COMPATIBILITY","SEMANTIC_QUANTITY_MISMATCH","source time bounds differ from EWP cumulative-mass observer",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"clock_gate":U},context=True),
 m("M-TOLERANCE","P-Q-CONST","E-FLOW-TOL","DOCUMENTATION_ONLY_COMPATIBILITY","REQUIRES_NUMERICAL_METHOD_CHANGE","source flow never maps to numerical tolerances",gates={"physical_quantity_gate":F,"unit_basis_gate":F,"no_governing_physics_change_gate":F}),
 ]

def dump(path,obj): path.write_text(json.dumps(obj,indent=2,sort_keys=True)+"\n")
def write_csv(path,rows,fields):
 with path.open("w",newline="",encoding="utf-8") as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)

def generate():
 OUT.mkdir(parents=True,exist_ok=True); regs=registry(); maps=mappings()
 contract={"task_id":TASK,"owner_authorization_token":"XSV-PANNUSCH-EWP-INPUT-MAPPING-001-OWNER-AUTHORIZED-AFTER-SCI-MD-PANNUSCH-FLOW-HISTORY-001-MERGE-2026-09-01","activation_precondition":"SCI_MD_PANNUSCH_FLOW_HISTORY_001_FLOW_AUTHORITY_INELIGIBLE present on origin/main","scientific_question":"Can any source-authorized Pannusch input map to an existing EWP input without inference, fitting, reconstruction, defaults, coupling, or physics change?","scope":"source authority and existing-interface semantics qualification","exclusions":["solver execution","OpenFOAM","calibration/refit","pressure-flow inference","history reconstruction","default or lock changes","model coupling"],"change_declaration":"NO_GOVERNING_PHYSICS_CHANGE","claim_ceiling":CLAIM,"accepted_mapping_classes":["DIRECT_PHYSICAL_QUANTITY_IDENTITY","EXACT_UNIT_CONVERSION","SOURCE_DEFINED_BASIS_CONVERSION"],"rejection_classes":sorted(set(x["mapping_classification"] for x in maps if x["operationally_qualified"]=="false")),"global_disposition_rules":"A iff operational set nonempty; B iff none and context set nonempty; C mixed negative without context; D only if all operational candidates authority-blocked; E authority unavailable","positive_result_restrictions":"partial adapter only; execution separately authorized","null_result_handling":"preserve independent input treatments; no adapter","prohibited_predecessor_evidence":["C07/C08 reconstructed schedules","MassData.flow as inlet flow","/0.98 flow","beverage outlet as inlet","pressure-derived Q","chemistry scoring"]}
 dump(OUT/"TASK_CONTRACT.json",contract)
 authority={"task_id":TASK,"ewp_base_commit":"7c79c8c6bf4670cb8ade7fb107ecdfd73afa827e","ewp_base_tree":"808abec7b2e9f5ca6cd42d5786daa293af627f88","predecessor_merge_commit":"7c79c8c6bf4670cb8ade7fb107ecdfd73afa827e","predecessor_merged_tree":"808abec7b2e9f5ca6cd42d5786daa293af627f88","puckworks_authority_commit":"2058d0e947ee9eb92c52d64f6165b810f1fb4732","puckworks_authority_tree":"a6ffb312473b15be43c1571a893b19873ea47c5a","branch_starting_commit":"7c79c8c6bf4670cb8ade7fb107ecdfd73afa827e","branch_starting_tree":"808abec7b2e9f5ca6cd42d5786daa293af627f88","recorded_at_utc":"2026-09-01T00:00:00Z","clean_state_evidence":{"ewp_active_checkout":"clean_before_worktree","task_worktree":"clean_at_creation","puckworks_active_checkout":"clean","authority_worktree":"detached_exact_commit"},"owner_authorization_token":contract["owner_authorization_token"],"change_declaration":"NO_GOVERNING_PHYSICS_CHANGE","lock_dependency_evidence":{"runtime_lock_commit":"fc61c4670ec7bf801e40bb391aab16048b8da26b","runtime_lock_unchanged":True,"merged_predecessor_exact_analysis_authority_takes_precedence":True},"relevant_source_file_sha256":{"docs/cards/pannusch2024.md":"e53d7bbfe682e799e04436b2ba91389dd2982c65ce0e04e2063ac15482c9c220","puckworks/models/pannusch2024/solver.py":"8f0f0108a8c44e0abbc32ca6ada676baf579a4f78265a3f7b53b38f118fa2bb4","puckworks/models/pannusch2024/closures.py":"9d144765200b66422e72218f8ceff5d5ca531da88150fa71d023bbc490b20cf1","puckworks/data/pannusch2024/source_inputs.csv":"15b9f765d49abe45d6788d7c7891b0695fca185d9c614d122e393993ec06a83c","puckworks/data/pannusch2024/prediction_conditions.csv":"a1efcf9ce876101be373a3b5955193dbf5a2075aef2e3b65dc0c83e80bbb3ee5","puckworks/data/pannusch2024/table2_fitted_params.csv":"318e1440d2922dfe98ddc06efe89de8fcd70c65f49ae9a8b92bc1123bd26a409"},"rights_redistribution_status":"CC-BY-NC-3.0 source inspected; only derived facts, locators, hashes, and classifications recorded","no_local_path_assertion":True,"no_puckworks_mutation_assertion":True}
 dump(OUT/"REPOSITORY_AUTHORITY.json",authority);write_csv(OUT/"INPUT_REGISTRY.csv",regs,REG_FIELDS);write_csv(OUT/"MAPPING_MATRIX.csv",maps,MAP_FIELDS)
 getcontext().prec=40; numeric=[]
 for s in ("1.0","1.7","2.0","2.3","3.0"):
  q=Decimal(s);v=q*Decimal("0.000001");back=v/Decimal("0.000001")
  numeric.append({"source_numeric_value":s,"source_units":"mL/s table label","hypothesis":"H_VOL_ONLY_NOT_AUTHORIZED_FOR_MAPPING","exact_conversion_expression":"Q_m3_s = Q_mL_s * 1e-6","converted_ewp_m3_s":str(v),"inverse_converted_value":str(back),"round_trip_absolute_error":str(abs(back-q)),"round_trip_relative_error":"0","constants":{"mL_to_m3":"1e-6 exact SI"},"density_enters":False,"area_enters":False,"porosity_enters":False,"mapping_use_authorized":False})
 audit={"task_id":TASK,"authoritative_adjudication":"H_UNRESOLVED","authoritative_source_flow_quantity":"programmed machine command; physical mass-versus-volume basis unresolved in implementation chain","authoritative_units":"table/schema label mL/s conflicts with Python mass/density conversion","hypotheses":{"H_VOL":{"expression":"Q_m3_s=Q_mL_s*1e-6","status":"LABEL_SUPPORTED_IMPLEMENTATION_CONFLICT"},"H_MASS":{"expression":"Q_m3_s=(Q_g_s*1e-3)/rho_kg_m3","status":"IMPLEMENTATION_FORM_SUGGESTS_BUT_SOURCE_DOES_NOT_AUTHORIZE"},"H_NUMERIC_WATER_EQUIVALENT":{"status":"NOT_SOURCE_AUTHORIZED"},"H_UNRESOLVED":{"status":"SELECTED_FAIL_CLOSED"}},"end_to_end_trace":["prediction_conditions.csv flow_start_mL_s/flow_end_mL_s: programmed mL/s labels","released MATLAB authority: source locators retained in source_inputs.csv; no unambiguous mass/volume basis closure","Puckworks schema: programmed values, not puck-face measurements","solver.py simulate_fractions(flow_mL_s)","solver.py q=flow_mL_s/1000/RHO/ACS","q passed as superficial velocity; v_l=q/ALPHA_L","fraction volume integration multiplies q*ACS*TC*1e6","EWP volumetricFlowRateM3PerS requires full-basket m3/s"],"numeric_checks":numeric,"mass_hypothesis_density":{"rho_kg_m3":"980","authority":"SOURCE_FIXED_MODEL_CONSTANT_NOT_AUTHORIZED_AS_INPUT_BASIS_CONVERSION","mapping_use_authorized":False},"source_condition_restrictions":{"constant_candidates":["PRED-C01","PRED-C02","PRED-C03","PRED-C04","PRED-C05","PRED-C06"],"qualified":[],"C07_C08_histories_excluded":True,"MassData_flow_excluded":True,"plotted_div_0_98_excluded":True,"beverage_outlet_excluded":True,"clock_alignment_inference_prohibited":True},"ewp_target":{"key":"prescribedFlowBoundary.volumetricFlowRateM3PerS","quantity":"finite nonnegative full-basket volumetric flow","area_applied":False,"porosity_applied":False,"eligibility":["initially saturated","static Darcy hydraulics","no wetting front","no pressure ramp","no lumped compliance","no Forchheimer","no compaction","no evolving permeability","no radial profile","default disabled","EWP tolerances remain independent"]},"failure_classification":"UNIT_OR_BASIS_UNRESOLVED"}
 dump(OUT/"UNIT_BASIS_AUDIT.json",audit)
 cls=Counter(x["mapping_classification"] for x in maps); failed=Counter()
 for x in maps:
  for k,v in x.items():
   if k.endswith("_gate") and v in {"FAIL","UNRESOLVED"}:failed[k+":"+v]+=1
 op=[x["mapping_id"] for x in maps if x["operationally_qualified"]=="true"];ctx=[x["mapping_id"] for x in maps if x["context_compatible"]=="true"]
 decision={"task_id":TASK,"scientific_disposition":DISP,"operationally_qualified_mapping_ids":op,"context_only_compatibility_ids":ctx,"rejected_mapping_ids":[x["mapping_id"] for x in maps if x["mapping_id"] not in op],"counts_by_classification":dict(sorted(cls.items())),"counts_by_failed_gate":dict(sorted(failed.items())),"independent_input_treatments_preserved":True,"materializer_implemented":False,"claim_ceiling":CLAIM,"no_physics_change_result":True,"no_default_change_result":True,"no_puckworks_lock_change_result":True,"separately_authorized_next_action":None,"claims":["SOURCE_INTERNAL","TARGET_EXPOSED","NOT INDEPENDENT VALIDATION","NOT PHYSICAL VALIDATION","NOT HYDRAULIC VALIDATION","NOT PUCK_FACE_FLOW VALIDATION","NOT PRESSURE_FLOW_VALIDATION","NOT CHEMISTRY VALIDATION","NOT MODEL COUPLING","NOT PRODUCTION QUALIFICATION","NO PRODUCTION ADOPTION"]}
 dump(OUT/"MAPPING_DECISION.json",decision)
 summary={"task_id":TASK,"disposition":DISP,"operational_mapping_count":len(op),"context_compatibility_count":len(ctx),"rejected_mapping_count":len(maps)-len(op),"registry_count":len(regs),"mapping_count":len(maps),"flow_unit_basis_result":"H_UNRESOLVED_FAIL_CLOSED_UNIT_OR_BASIS_UNRESOLVED","materializer_present":False,"independent_input_treatments_preserved":True,"claim_ceiling":CLAIM,"change_declaration":"NO_GOVERNING_PHYSICS_CHANGE","programme_action":"PRESERVE_PANNUSCH_AND_EWP_INDEPENDENT_INPUT_TREATMENTS"}
 dump(OUT/"summary.json",summary)
 result=f"""# XSV-PANNUSCH-EWP-INPUT-MAPPING-001 result\n\n**Disposition:** `{DISP}`. The operational mapping set is empty. **PRESERVE_PANNUSCH_AND_EWP_INDEPENDENT_INPUT_TREATMENTS.**\n\n## Authority and question\n\nEWP base and predecessor merge: `7c79c8c6bf4670cb8ade7fb107ecdfd73afa827e` / tree `808abec7b2e9f5ca6cd42d5786daa293af627f88`. Exact merged Pannusch authority: Puckworks `2058d0e947ee9eb92c52d64f6165b810f1fb4732` / tree `a6ffb312473b15be43c1571a893b19873ea47c5a`. This audit asked whether a source-authorized Pannusch primitive can populate an existing EWP consumer by identity, exact units, or an explicitly source-defined basis conversion without inference, refit, reconstruction, defaults, coupling, or physics change.\n\n## Method and result\n\nThe complete bounded Pannusch inventory and current EWP runtime consumers were source-located, role-classified, and compared through the frozen gates. No operational candidate passed all gates. Context-only compatibilities record nominal 58 mm geometry, 20 g scenario, initially saturated state, clean inlet, source temperature metadata, particle context, and observer/run-control facts. They authorize no EWP execution. Chemistry, grind, porosity, diffusivity, viscosity, capacity, inventory, and extraction-rate transfers were rejected for authority, quantity/basis, consumer, state, constitutive, or calibration reasons. No materializer was created.\n\n## Critical flow finding\n\nSource tables label programmed flow as mL/s, but `solver.py` computes superficial velocity as `flow_mL_s / 1000 / RHO / ACS`. The source authority does not unambiguously establish volumetric flow, mass flow, or a numerical water-equivalent convention with the exact density basis. `H_UNRESOLVED` therefore fails closed as `UNIT_OR_BASIS_UNRESOLVED`. Exact hypothetical SI mL/s round trips are recorded only to expose the competing convention; they are not accepted mappings. C07/C08 endpoints, `MassData.flow`, `/0.98`, beverage derivatives, pressure inference, and clock reconstruction remain excluded.\n\n## Tests and claim ceiling\n\nFocused and repository acceptance evidence is recorded in `PACKAGE_QA_STATUS.json`. No OpenFOAM or Pannusch chemistry execution occurred; production solver source, equations, defaults, calibrated parameters, and the Puckworks lock are unchanged.\n\nClaim ceiling: `{CLAIM}`. SOURCE_INTERNAL; TARGET_EXPOSED; NOT INDEPENDENT VALIDATION; NOT PHYSICAL VALIDATION; NOT HYDRAULIC VALIDATION; NOT PUCK_FACE_FLOW VALIDATION; NOT PRESSURE_FLOW_VALIDATION; NOT CHEMISTRY VALIDATION; NOT MODEL COUPLING; NOT PRODUCTION QUALIFICATION; NO PRODUCTION ADOPTION.\n"""
 (OUT/"RESULT.md").write_text(result)

if __name__=="__main__":generate()
